#ifndef __swperf_h
#define __swperf_h 
#include <stdio.h>
#include <stdlib.h>
#ifdef __cplusplus
extern "C" {
#endif
#define ID_offset(x) (x-100)
#define D_CNTLIST_SIZE 206
extern void penv_host0_retire_inst_init();
extern void penv_host0_retire_inst_count(unsigned long *count);
extern void penv_host0_retire_inst_mem_init();
extern void penv_host0_retire_inst_mem_count(unsigned long *count);
extern void penv_host0_retire_inst_read_init();
extern void penv_host0_retire_inst_read_count(unsigned long *count);
extern void penv_host0_jump_inst_init();
extern void penv_host0_jump_inst_count(unsigned long *count);
extern void penv_host0_jump_inst_con_init();
extern void penv_host0_jump_inst_con_count(unsigned long *count);
extern void penv_host0_jump_inst_uncon_init();
extern void penv_host0_jump_inst_uncon_count(unsigned long *count);
extern void penv_host0_call_and_jsr_init();
extern void penv_host0_call_and_jsr_count(unsigned long *count);
extern void penv_host0_inst_ret_init();
extern void penv_host0_inst_ret_count(unsigned long *count);
extern void penv_host0_cycle_init();
extern void penv_host0_cycle_count(unsigned long *count);
extern void penv_host0_itb_access_init();
extern void penv_host0_itb_access_count(unsigned long *count);
extern void penv_host0_dtb_access_init();
extern void penv_host0_dtb_access_count(unsigned long *count);
extern void penv_host0_icache_access_init();
extern void penv_host0_icache_access_count(unsigned long *count);
extern void penv_host0_dcache_access_init();
extern void penv_host0_dcache_access_count(unsigned long *count);
extern void penv_host0_scache_access_init();
extern void penv_host0_scache_access_count(unsigned long *count);
extern void penv_host0_mem_access_init();
extern void penv_host0_mem_access_count(unsigned long *count);
extern void penv_host0_prob_req_init();
extern void penv_host0_prob_req_count(unsigned long *count);
extern void penv_host1_cyc_empty_init();
extern void penv_host1_cyc_empty_count(unsigned long *count);
extern void penv_host1_cyc_halt_int_init();
extern void penv_host1_cyc_halt_int_count(unsigned long *count);
extern void penv_host1_cyc_halt_float_init();
extern void penv_host1_cyc_halt_float_count(unsigned long *count);
extern void penv_host1_cyc_halt_iwq_init();
extern void penv_host1_cyc_halt_iwq_count(unsigned long *count);
extern void penv_host1_cyc_halt_fwq_init();
extern void penv_host1_cyc_halt_fwq_count(unsigned long *count);
extern void penv_host1_cyc_halt_rob_init();
extern void penv_host1_cyc_halt_rob_count(unsigned long *count);
extern void penv_host1_cyc_halt_lq_init();
extern void penv_host1_cyc_halt_lq_count(unsigned long *count);
extern void penv_host1_cyc_halt_sq_init();
extern void penv_host1_cyc_halt_sq_count(unsigned long *count);
extern void penv_host1_cyc_unsend_init();
extern void penv_host1_cyc_unsend_count(unsigned long *count);
extern void penv_host1_cyc_block_iq0_init();
extern void penv_host1_cyc_block_iq0_count(unsigned long *count);
extern void penv_host1_cyc_retire_fail_rob_init();
extern void penv_host1_cyc_retire_fail_rob_count(unsigned long *count);
extern void penv_host1_fail_prejump_inst_init();
extern void penv_host1_fail_prejump_inst_count(unsigned long *count);
extern void penv_host1_fail_prejump_inst_con_init();
extern void penv_host1_fail_prejump_inst_con_count(unsigned long *count);
extern void penv_host1_fail_prejump_inst_uncon_init();
extern void penv_host1_fail_prejump_inst_uncon_count(unsigned long *count);
extern void penv_host1_fail_prejump_inst_call_jmp_init();
extern void penv_host1_fail_prejump_inst_call_jmp_count(unsigned long *count);
extern void penv_host1_fail_prejump_inst_ret_init();
extern void penv_host1_fail_prejump_inst_ret_count(unsigned long *count);
extern void penv_host1_scache_miss_init();
extern void penv_host1_scache_miss_count(unsigned long *count);
extern void penv_host1_scache_from_other_chip_tcache_init();
extern void penv_host1_scache_from_other_chip_tcache_count(unsigned long *count);
extern void penv_host1_scache_from_chip_mem_init();
extern void penv_host1_scache_from_chip_mem_count(unsigned long *count);
extern void penv_host1_scache_from_other_chip_mem_init();
extern void penv_host1_scache_from_other_chip_mem_count(unsigned long *count);
extern void penv_host1_scache_coherenthit_init();
extern void penv_host1_scache_coherenthit_count(unsigned long *count);
extern void penv_host1_fail_prebpu_init();
extern void penv_host1_fail_prebpu_count(unsigned long *count);
extern void penv_host1_icache_miss_init();
extern void penv_host1_icache_miss_count(unsigned long *count);
extern void penv_host1_itb_miss_init();
extern void penv_host1_itb_miss_count(unsigned long *count);
extern void penv_host1_dtb_l1miss_l2hit_init();
extern void penv_host1_dtb_l1miss_l2hit_count(unsigned long *count);
extern void penv_host1_conflict_side_init();
extern void penv_host1_conflict_side_count(unsigned long *count);
extern void penv_host1_conflict_maf_init();
extern void penv_host1_conflict_maf_count(unsigned long *count);
extern void penv_host1_conflict_index_init();
extern void penv_host1_conflict_index_count(unsigned long *count);
extern void penv_host1_conflict_dcache_port0_init();
extern void penv_host1_conflict_dcache_port0_count(unsigned long *count);
extern void penv_host1_conflict_dcache_port1_init();
extern void penv_host1_conflict_dcache_port1_count(unsigned long *count);
extern void penv_host1_conflict_wreg_init();
extern void penv_host1_conflict_wreg_count(unsigned long *count);
extern void penv_host1_scache_from_chip_tcache_init();
extern void penv_host1_scache_from_chip_tcache_count(unsigned long *count);
extern void penv_host1_cyc_block_iq1_init();
extern void penv_host1_cyc_block_iq1_count(unsigned long *count);
extern void penv_host1_cyc_block_iq2_init();
extern void penv_host1_cyc_block_iq2_count(unsigned long *count);
extern void penv_host1_cyc_block_aq0_init();
extern void penv_host1_cyc_block_aq0_count(unsigned long *count);
extern void penv_host1_cyc_block_aq1_init();
extern void penv_host1_cyc_block_aq1_count(unsigned long *count);
extern void penv_host1_cyc_block_isq_init();
extern void penv_host1_cyc_block_isq_count(unsigned long *count);
extern void penv_host1_cyc_block_fsq_init();
extern void penv_host1_cyc_block_fsq_count(unsigned long *count);
extern void penv_host1_cyc_block_fq0_init();
extern void penv_host1_cyc_block_fq0_count(unsigned long *count);
extern void penv_host1_cyc_block_fq1_init();
extern void penv_host1_cyc_block_fq1_count(unsigned long *count);
extern void penv_host1_cyc_block_awq_init();
extern void penv_host1_cyc_block_awq_count(unsigned long *count);
extern void penv_host1_dtb_smiss_init();
extern void penv_host1_dtb_smiss_count(unsigned long *count);
extern void penv_host1_dtb_dmiss_init();
extern void penv_host1_dtb_dmiss_count(unsigned long *count);
extern void penv_host1_dcache_miss_init();
extern void penv_host1_dcache_miss_count(unsigned long *count);
extern void penv_host1_fall_load_load_init();
extern void penv_host1_fall_load_load_count(unsigned long *count);
extern void penv_host1_fall_load_store_init();
extern void penv_host1_fall_load_store_count(unsigned long *count);
extern void penv_host1_fall_init();
extern void penv_host1_fall_count(unsigned long *count);
extern void penv_host1_memisnt_cachemiss_nopre_init();
extern void penv_host1_memisnt_cachemiss_nopre_count(unsigned long *count);
extern void penv_host1_float_muletc_init();
extern void penv_host1_float_muletc_count(unsigned long *count);
extern void penv_host1_float_divetc_init();
extern void penv_host1_float_divetc_count(unsigned long *count);
extern void penv_host1_float_memacc_init();
extern void penv_host1_float_memacc_count(unsigned long *count);
extern void penv_host1_float_vector_memacc_init();
extern void penv_host1_float_vector_memacc_count(unsigned long *count);
extern void penv_host1_vector_ops_init();
extern void penv_host1_vector_ops_count(unsigned long *count);
extern void penv_host1_vector_memacc_init();
extern void penv_host1_vector_memacc_count(unsigned long *count);
extern void penv_host_retic_retire_inst_init();
extern void penv_host_retic_retire_inst_count(unsigned long *count);
extern void penv_host_imisc_icache_miss_init();
extern void penv_host_imisc_icache_miss_count(unsigned long *count);
extern void penv_host_iacc_icache_access_init();
extern void penv_host_iacc_icache_access_count(unsigned long *count);
extern void penv_host_dmisc_dcache_miss_init();
extern void penv_host_dmisc_dcache_miss_count(unsigned long *count);
extern void penv_host_dacc_dcache_access_init();
extern void penv_host_dacc_dcache_access_count(unsigned long *count);
extern void penv_slave0_cycle_init();
extern void penv_slave0_cycle_count(unsigned long *count);
extern void penv_slave0_cycle_init();
extern void penv_slave0_cycle_count(unsigned long *count);
extern void penv_slave1_inst_init();
extern void penv_slave1_inst_count(unsigned long *count);
extern void penv_slave1_inst_lan_init();
extern void penv_slave1_inst_lan_count(unsigned long *count);
extern void penv_slave1_inst_cbr_init();
extern void penv_slave1_inst_cbr_count(unsigned long *count);
extern void penv_slave1_inst_memacc_init();
extern void penv_slave1_inst_memacc_count(unsigned long *count);
extern void penv_slave1_inst_ldmaccess_init();
extern void penv_slave1_inst_ldmaccess_count(unsigned long *count);
extern void penv_slave1_dcache_hit_ldm_init();
extern void penv_slave1_dcache_hit_ldm_count(unsigned long *count);
extern void penv_slave1_dcache_access_init();
extern void penv_slave1_dcache_access_count(unsigned long *count);
extern void penv_slave1_rmaccess_init();
extern void penv_slave1_rmaccess_count(unsigned long *count);
extern void penv_slave1_inst_pipe0_init();
extern void penv_slave1_inst_pipe0_count(unsigned long *count);
extern void penv_slave1_inst_scalar_float_other_init();
extern void penv_slave1_inst_scalar_float_other_count(unsigned long *count);
extern void penv_slave1_req_dma_rma_init();
extern void penv_slave1_req_dma_rma_count(unsigned long *count);
extern void penv_slave1_req_dma_init();
extern void penv_slave1_req_dma_count(unsigned long *count);
extern void penv_slave1_req_rma_init();
extern void penv_slave1_req_rma_count(unsigned long *count);
extern void penv_slave1_req_io_init();
extern void penv_slave1_req_io_count(unsigned long *count);
extern void penv_slave1_inst_scalar_half_float_other_init();
extern void penv_slave1_inst_scalar_half_float_other_count(unsigned long *count);
extern void penv_slave1_inst_init();
extern void penv_slave1_inst_count(unsigned long *count);
extern void penv_slave1_inst_lan_init();
extern void penv_slave1_inst_lan_count(unsigned long *count);
extern void penv_slave1_inst_cbr_init();
extern void penv_slave1_inst_cbr_count(unsigned long *count);
extern void penv_slave1_inst_memacc_init();
extern void penv_slave1_inst_memacc_count(unsigned long *count);
extern void penv_slave1_inst_ldmaccess_init();
extern void penv_slave1_inst_ldmaccess_count(unsigned long *count);
extern void penv_slave1_dcache_hit_ldm_init();
extern void penv_slave1_dcache_hit_ldm_count(unsigned long *count);
extern void penv_slave1_dcache_access_init();
extern void penv_slave1_dcache_access_count(unsigned long *count);
extern void penv_slave1_rmaccess_init();
extern void penv_slave1_rmaccess_count(unsigned long *count);
extern void penv_slave1_inst_pipe0_init();
extern void penv_slave1_inst_pipe0_count(unsigned long *count);
extern void penv_slave1_inst_scalar_float_other_init();
extern void penv_slave1_inst_scalar_float_other_count(unsigned long *count);
extern void penv_slave1_req_dma_rma_init();
extern void penv_slave1_req_dma_rma_count(unsigned long *count);
extern void penv_slave1_req_dma_init();
extern void penv_slave1_req_dma_count(unsigned long *count);
extern void penv_slave1_req_rma_init();
extern void penv_slave1_req_rma_count(unsigned long *count);
extern void penv_slave1_req_io_init();
extern void penv_slave1_req_io_count(unsigned long *count);
extern void penv_slave1_inst_scalar_half_float_other_init();
extern void penv_slave1_inst_scalar_half_float_other_count(unsigned long *count);
extern void penv_slave2_l1ic_access_init();
extern void penv_slave2_l1ic_access_count(unsigned long *count);
extern void penv_slave2_l1ic_misstime_init();
extern void penv_slave2_l1ic_misstime_count(unsigned long *count);
extern void penv_slave2_cyc_doublelaunhc_init();
extern void penv_slave2_cyc_doublelaunhc_count(unsigned long *count);
extern void penv_slave2_inst_jump_con_init();
extern void penv_slave2_inst_jump_con_count(unsigned long *count);
extern void penv_slave2_pre_sequence_init();
extern void penv_slave2_pre_sequence_count(unsigned long *count);
extern void penv_slave2_ldm_pipedirect_init();
extern void penv_slave2_ldm_pipedirect_count(unsigned long *count);
extern void penv_slave2_cyc_ldmconflict_init();
extern void penv_slave2_cyc_ldmconflict_count(unsigned long *count);
extern void penv_slave2_dcache_evict_ldm_init();
extern void penv_slave2_dcache_evict_ldm_count(unsigned long *count);
extern void penv_slave2_dcache_miss_init();
extern void penv_slave2_dcache_miss_count(unsigned long *count);
extern void penv_slave2_gld_init();
extern void penv_slave2_gld_count(unsigned long *count);
extern void penv_slave2_inst_pipe0_int_init();
extern void penv_slave2_inst_pipe0_int_count(unsigned long *count);
extern void penv_slave2_inst_scalar_int_init();
extern void penv_slave2_inst_scalar_int_count(unsigned long *count);
extern void penv_slave2_inst_scalar_float_addetc_init();
extern void penv_slave2_inst_scalar_float_addetc_count(unsigned long *count);
extern void penv_slave2_req_rsyn_init();
extern void penv_slave2_req_rsyn_count(unsigned long *count);
extern void penv_slave2_req_dma_init();
extern void penv_slave2_req_dma_count(unsigned long *count);
extern void penv_slave2_req_dma_put_init();
extern void penv_slave2_req_dma_put_count(unsigned long *count);
extern void penv_slave2_req_rma_put_init();
extern void penv_slave2_req_rma_put_count(unsigned long *count);
extern void penv_slave2_req_l1ic_ram_read_init();
extern void penv_slave2_req_l1ic_ram_read_count(unsigned long *count);
extern void penv_slave2_inst_scalar_half_float_addetc_init();
extern void penv_slave2_inst_scalar_half_float_addetc_count(unsigned long *count);
extern void penv_slave2_l1ic_access_init();
extern void penv_slave2_l1ic_access_count(unsigned long *count);
extern void penv_slave2_l1ic_misstime_init();
extern void penv_slave2_l1ic_misstime_count(unsigned long *count);
extern void penv_slave2_cyc_doublelaunhc_init();
extern void penv_slave2_cyc_doublelaunhc_count(unsigned long *count);
extern void penv_slave2_inst_jump_con_init();
extern void penv_slave2_inst_jump_con_count(unsigned long *count);
extern void penv_slave2_pre_sequence_init();
extern void penv_slave2_pre_sequence_count(unsigned long *count);
extern void penv_slave2_ldm_pipedirect_init();
extern void penv_slave2_ldm_pipedirect_count(unsigned long *count);
extern void penv_slave2_cyc_ldmconflict_init();
extern void penv_slave2_cyc_ldmconflict_count(unsigned long *count);
extern void penv_slave2_dcache_evict_ldm_init();
extern void penv_slave2_dcache_evict_ldm_count(unsigned long *count);
extern void penv_slave2_dcache_miss_init();
extern void penv_slave2_dcache_miss_count(unsigned long *count);
extern void penv_slave2_gld_init();
extern void penv_slave2_gld_count(unsigned long *count);
extern void penv_slave2_inst_pipe0_int_init();
extern void penv_slave2_inst_pipe0_int_count(unsigned long *count);
extern void penv_slave2_inst_scalar_int_init();
extern void penv_slave2_inst_scalar_int_count(unsigned long *count);
extern void penv_slave2_inst_scalar_float_addetc_init();
extern void penv_slave2_inst_scalar_float_addetc_count(unsigned long *count);
extern void penv_slave2_req_rsyn_init();
extern void penv_slave2_req_rsyn_count(unsigned long *count);
extern void penv_slave2_req_dma_init();
extern void penv_slave2_req_dma_count(unsigned long *count);
extern void penv_slave2_req_dma_put_init();
extern void penv_slave2_req_dma_put_count(unsigned long *count);
extern void penv_slave2_req_rma_put_init();
extern void penv_slave2_req_rma_put_count(unsigned long *count);
extern void penv_slave2_req_l1ic_ram_read_init();
extern void penv_slave2_req_l1ic_ram_read_count(unsigned long *count);
extern void penv_slave2_inst_scalar_half_float_addetc_init();
extern void penv_slave2_inst_scalar_half_float_addetc_count(unsigned long *count);
extern void penv_slave3_l1ic_miss_init();
extern void penv_slave3_l1ic_miss_count(unsigned long *count);
extern void penv_slave3_l0ic_bubble_init();
extern void penv_slave3_l0ic_bubble_count(unsigned long *count);
extern void penv_slave3_cyc_launhc_none_init();
extern void penv_slave3_cyc_launhc_none_count(unsigned long *count);
extern void penv_slave3_fail_prejump_inst_con_init();
extern void penv_slave3_fail_prejump_inst_con_count(unsigned long *count);
extern void penv_slave3_prejump_forward_init();
extern void penv_slave3_prejump_forward_count(unsigned long *count);
extern void penv_slave3_dcache_hit_ldm_init();
extern void penv_slave3_dcache_hit_ldm_count(unsigned long *count);
extern void penv_slave3_ldm_pipe_init();
extern void penv_slave3_ldm_pipe_count(unsigned long *count);
extern void penv_slave3_writeldm_dma_rma_init();
extern void penv_slave3_writeldm_dma_rma_count(unsigned long *count);
extern void penv_slave3_req_dcache_evict_init();
extern void penv_slave3_req_dcache_evict_count(unsigned long *count);
extern void penv_slave3_gst_init();
extern void penv_slave3_gst_count(unsigned long *count);
extern void penv_slave3_inst_pipe0_float_init();
extern void penv_slave3_inst_pipe0_float_count(unsigned long *count);
extern void penv_slave3_inst_scalar_float_init();
extern void penv_slave3_inst_scalar_float_count(unsigned long *count);
extern void penv_slave3_inst_scalar_float_muletc_init();
extern void penv_slave3_inst_scalar_float_muletc_count(unsigned long *count);
extern void penv_slave3_req_csyn_init();
extern void penv_slave3_req_csyn_count(unsigned long *count);
extern void penv_slave3_req_rma_init();
extern void penv_slave3_req_rma_count(unsigned long *count);
extern void penv_slave3_req_dma_get_init();
extern void penv_slave3_req_dma_get_count(unsigned long *count);
extern void penv_slave3_req_rma_get_init();
extern void penv_slave3_req_rma_get_count(unsigned long *count);
extern void penv_slave3_req_ldm_ram_read_init();
extern void penv_slave3_req_ldm_ram_read_count(unsigned long *count);
extern void penv_slave3_inst_scalar_half_float_muletc_init();
extern void penv_slave3_inst_scalar_half_float_muletc_count(unsigned long *count);
extern void penv_slave3_l1ic_miss_init();
extern void penv_slave3_l1ic_miss_count(unsigned long *count);
extern void penv_slave3_l0ic_bubble_init();
extern void penv_slave3_l0ic_bubble_count(unsigned long *count);
extern void penv_slave3_cyc_launhc_none_init();
extern void penv_slave3_cyc_launhc_none_count(unsigned long *count);
extern void penv_slave3_fail_prejump_inst_con_init();
extern void penv_slave3_fail_prejump_inst_con_count(unsigned long *count);
extern void penv_slave3_prejump_forward_init();
extern void penv_slave3_prejump_forward_count(unsigned long *count);
extern void penv_slave3_dcache_hit_ldm_init();
extern void penv_slave3_dcache_hit_ldm_count(unsigned long *count);
extern void penv_slave3_ldm_pipe_init();
extern void penv_slave3_ldm_pipe_count(unsigned long *count);
extern void penv_slave3_writeldm_dma_rma_init();
extern void penv_slave3_writeldm_dma_rma_count(unsigned long *count);
extern void penv_slave3_req_dcache_evict_init();
extern void penv_slave3_req_dcache_evict_count(unsigned long *count);
extern void penv_slave3_gst_init();
extern void penv_slave3_gst_count(unsigned long *count);
extern void penv_slave3_inst_pipe0_float_init();
extern void penv_slave3_inst_pipe0_float_count(unsigned long *count);
extern void penv_slave3_inst_scalar_float_init();
extern void penv_slave3_inst_scalar_float_count(unsigned long *count);
extern void penv_slave3_inst_scalar_float_muletc_init();
extern void penv_slave3_inst_scalar_float_muletc_count(unsigned long *count);
extern void penv_slave3_req_csyn_init();
extern void penv_slave3_req_csyn_count(unsigned long *count);
extern void penv_slave3_req_rma_init();
extern void penv_slave3_req_rma_count(unsigned long *count);
extern void penv_slave3_req_dma_get_init();
extern void penv_slave3_req_dma_get_count(unsigned long *count);
extern void penv_slave3_req_rma_get_init();
extern void penv_slave3_req_rma_get_count(unsigned long *count);
extern void penv_slave3_req_ldm_ram_read_init();
extern void penv_slave3_req_ldm_ram_read_count(unsigned long *count);
extern void penv_slave3_inst_scalar_half_float_muletc_init();
extern void penv_slave3_inst_scalar_half_float_muletc_count(unsigned long *count);
extern void penv_slave4_dcache_access_init();
extern void penv_slave4_dcache_access_count(unsigned long *count);
extern void penv_slave4_cyc_launhc_none_buffer_init();
extern void penv_slave4_cyc_launhc_none_buffer_count(unsigned long *count);
extern void penv_slave4_inst_pipe0launhc_init();
extern void penv_slave4_inst_pipe0launhc_count(unsigned long *count);
extern void penv_slave4_cyc_pipe0launhcnone_inst_init();
extern void penv_slave4_cyc_pipe0launhcnone_inst_count(unsigned long *count);
extern void penv_slave4_l1ic_misstime_init();
extern void penv_slave4_l1ic_misstime_count(unsigned long *count);
extern void penv_slave4_br_init();
extern void penv_slave4_br_count(unsigned long *count);
extern void penv_slave4_prejump_back_init();
extern void penv_slave4_prejump_back_count(unsigned long *count);
extern void penv_slave4_req_rscatter_memacc_init();
extern void penv_slave4_req_rscatter_memacc_count(unsigned long *count);
extern void penv_slave4_cyc_lscatter_memacc_unldm_init();
extern void penv_slave4_cyc_lscatter_memacc_unldm_count(unsigned long *count);
extern void penv_slave4_readldm_dma_rma_init();
extern void penv_slave4_readldm_dma_rma_count(unsigned long *count);
extern void penv_slave4_req_dcache_evict_alone_init();
extern void penv_slave4_req_dcache_evict_alone_count(unsigned long *count);
extern void penv_slave4_rld_init();
extern void penv_slave4_rld_count(unsigned long *count);
extern void penv_slave4_inst_pipe0_memacc_init();
extern void penv_slave4_inst_pipe0_memacc_count(unsigned long *count);
extern void penv_slave4_inst_scalar_memacc_init();
extern void penv_slave4_inst_scalar_memacc_count(unsigned long *count);
extern void penv_slave4_inst_scalar_float_divetc_init();
extern void penv_slave4_inst_scalar_float_divetc_count(unsigned long *count);
extern void penv_slave4_req_sync_p2p_init();
extern void penv_slave4_req_sync_p2p_count(unsigned long *count);
extern void penv_slave4_req_dma_fence_init();
extern void penv_slave4_req_dma_fence_count(unsigned long *count);
extern void penv_slave4_req_rma_fence_init();
extern void penv_slave4_req_rma_fence_count(unsigned long *count);
extern void penv_slave4_req_gpr_read_init();
extern void penv_slave4_req_gpr_read_count(unsigned long *count);
extern void penv_slave4_dcache_access_init();
extern void penv_slave4_dcache_access_count(unsigned long *count);
extern void penv_slave4_cyc_launhc_none_buffer_init();
extern void penv_slave4_cyc_launhc_none_buffer_count(unsigned long *count);
extern void penv_slave4_inst_pipe0launhc_init();
extern void penv_slave4_inst_pipe0launhc_count(unsigned long *count);
extern void penv_slave4_cyc_pipe0launhcnone_inst_init();
extern void penv_slave4_cyc_pipe0launhcnone_inst_count(unsigned long *count);
extern void penv_slave4_l1ic_misstime_init();
extern void penv_slave4_l1ic_misstime_count(unsigned long *count);
extern void penv_slave4_br_init();
extern void penv_slave4_br_count(unsigned long *count);
extern void penv_slave4_prejump_back_init();
extern void penv_slave4_prejump_back_count(unsigned long *count);
extern void penv_slave4_req_rscatter_memacc_init();
extern void penv_slave4_req_rscatter_memacc_count(unsigned long *count);
extern void penv_slave4_cyc_lscatter_memacc_unldm_init();
extern void penv_slave4_cyc_lscatter_memacc_unldm_count(unsigned long *count);
extern void penv_slave4_readldm_dma_rma_init();
extern void penv_slave4_readldm_dma_rma_count(unsigned long *count);
extern void penv_slave4_req_dcache_evict_alone_init();
extern void penv_slave4_req_dcache_evict_alone_count(unsigned long *count);
extern void penv_slave4_rld_init();
extern void penv_slave4_rld_count(unsigned long *count);
extern void penv_slave4_inst_pipe0_memacc_init();
extern void penv_slave4_inst_pipe0_memacc_count(unsigned long *count);
extern void penv_slave4_inst_scalar_memacc_init();
extern void penv_slave4_inst_scalar_memacc_count(unsigned long *count);
extern void penv_slave4_inst_scalar_float_divetc_init();
extern void penv_slave4_inst_scalar_float_divetc_count(unsigned long *count);
extern void penv_slave4_req_sync_p2p_init();
extern void penv_slave4_req_sync_p2p_count(unsigned long *count);
extern void penv_slave4_req_dma_fence_init();
extern void penv_slave4_req_dma_fence_count(unsigned long *count);
extern void penv_slave4_req_rma_fence_init();
extern void penv_slave4_req_rma_fence_count(unsigned long *count);
extern void penv_slave4_req_gpr_read_init();
extern void penv_slave4_req_gpr_read_count(unsigned long *count);
extern void penv_slave5_dcache_miss_init();
extern void penv_slave5_dcache_miss_count(unsigned long *count);
extern void penv_slave5_cyc_syn_wait_init();
extern void penv_slave5_cyc_syn_wait_count(unsigned long *count);
extern void penv_slave5_inst_pipe1launhc_init();
extern void penv_slave5_inst_pipe1launhc_count(unsigned long *count);
extern void penv_slave5_cyc_pipe1launhcnone_inst_init();
extern void penv_slave5_cyc_pipe1launhcnone_inst_count(unsigned long *count);
extern void penv_slave5_inst_l0ic_read_init();
extern void penv_slave5_inst_l0ic_read_count(unsigned long *count);
extern void penv_slave5_jmp_init();
extern void penv_slave5_jmp_count(unsigned long *count);
extern void penv_slave5_fail_pre_sequence_init();
extern void penv_slave5_fail_pre_sequence_count(unsigned long *count);
extern void penv_slave5_cyc_lscatter_memacc_unarbitrate_init();
extern void penv_slave5_cyc_lscatter_memacc_unarbitrate_count(unsigned long *count);
extern void penv_slave5_dcache_access_ldm_init();
extern void penv_slave5_dcache_access_ldm_count(unsigned long *count);
extern void penv_slave5_ldm_autoaddone_init();
extern void penv_slave5_ldm_autoaddone_count(unsigned long *count);
extern void penv_slave5_req_dcache_prefetch_init();
extern void penv_slave5_req_dcache_prefetch_count(unsigned long *count);
extern void penv_slave5_rst_init();
extern void penv_slave5_rst_count(unsigned long *count);
extern void penv_slave5_inst_pipe1_init();
extern void penv_slave5_inst_pipe1_count(unsigned long *count);
extern void penv_slave5_inst_vector_int_init();
extern void penv_slave5_inst_vector_int_count(unsigned long *count);
extern void penv_slave5_inst_vector_float_other_init();
extern void penv_slave5_inst_vector_float_other_count(unsigned long *count);
extern void penv_slave5_req_rma_fence_init();
extern void penv_slave5_req_rma_fence_count(unsigned long *count);
extern void penv_slave5_req_dma_fence_total_init();
extern void penv_slave5_req_dma_fence_total_count(unsigned long *count);
extern void penv_slave5_req_rma_fence_total_init();
extern void penv_slave5_req_rma_fence_total_count(unsigned long *count);
extern void penv_slave5_req_l1ic_ram_read_init();
extern void penv_slave5_req_l1ic_ram_read_count(unsigned long *count);
extern void penv_slave5_inst_vector_half_float_other_init();
extern void penv_slave5_inst_vector_half_float_other_count(unsigned long *count);
extern void penv_slave5_dcache_miss_init();
extern void penv_slave5_dcache_miss_count(unsigned long *count);
extern void penv_slave5_cyc_syn_wait_init();
extern void penv_slave5_cyc_syn_wait_count(unsigned long *count);
extern void penv_slave5_inst_pipe1launhc_init();
extern void penv_slave5_inst_pipe1launhc_count(unsigned long *count);
extern void penv_slave5_cyc_pipe1launhcnone_inst_init();
extern void penv_slave5_cyc_pipe1launhcnone_inst_count(unsigned long *count);
extern void penv_slave5_inst_l0ic_read_init();
extern void penv_slave5_inst_l0ic_read_count(unsigned long *count);
extern void penv_slave5_jmp_init();
extern void penv_slave5_jmp_count(unsigned long *count);
extern void penv_slave5_fail_pre_sequence_init();
extern void penv_slave5_fail_pre_sequence_count(unsigned long *count);
extern void penv_slave5_cyc_lscatter_memacc_unarbitrate_init();
extern void penv_slave5_cyc_lscatter_memacc_unarbitrate_count(unsigned long *count);
extern void penv_slave5_dcache_access_ldm_init();
extern void penv_slave5_dcache_access_ldm_count(unsigned long *count);
extern void penv_slave5_ldm_autoaddone_init();
extern void penv_slave5_ldm_autoaddone_count(unsigned long *count);
extern void penv_slave5_req_dcache_prefetch_init();
extern void penv_slave5_req_dcache_prefetch_count(unsigned long *count);
extern void penv_slave5_rst_init();
extern void penv_slave5_rst_count(unsigned long *count);
extern void penv_slave5_inst_pipe1_init();
extern void penv_slave5_inst_pipe1_count(unsigned long *count);
extern void penv_slave5_inst_vector_int_init();
extern void penv_slave5_inst_vector_int_count(unsigned long *count);
extern void penv_slave5_inst_vector_float_other_init();
extern void penv_slave5_inst_vector_float_other_count(unsigned long *count);
extern void penv_slave5_req_rma_fence_init();
extern void penv_slave5_req_rma_fence_count(unsigned long *count);
extern void penv_slave5_req_dma_fence_total_init();
extern void penv_slave5_req_dma_fence_total_count(unsigned long *count);
extern void penv_slave5_req_rma_fence_total_init();
extern void penv_slave5_req_rma_fence_total_count(unsigned long *count);
extern void penv_slave5_req_l1ic_ram_read_init();
extern void penv_slave5_req_l1ic_ram_read_count(unsigned long *count);
extern void penv_slave5_inst_vector_half_float_other_init();
extern void penv_slave5_inst_vector_half_float_other_count(unsigned long *count);
extern void penv_slave6_cyc_launhcnone_buffer_init();
extern void penv_slave6_cyc_launhcnone_buffer_count(unsigned long *count);
extern void penv_slave6_cyc_memb_wait_init();
extern void penv_slave6_cyc_memb_wait_count(unsigned long *count);
extern void penv_slave6_cyc_pipe0_noinst_init();
extern void penv_slave6_cyc_pipe0_noinst_count(unsigned long *count);
extern void penv_slave6_l0ic_bubble_init();
extern void penv_slave6_l0ic_bubble_count(unsigned long *count);
extern void penv_slave6_inst_conflag_init();
extern void penv_slave6_inst_conflag_count(unsigned long *count);
extern void penv_slave6_fail_prejump_forward_init();
extern void penv_slave6_fail_prejump_forward_count(unsigned long *count);
extern void penv_slave6_cyc_dcache_crq_init();
extern void penv_slave6_cyc_dcache_crq_count(unsigned long *count);
extern void penv_slave6_ldm_tbox_init();
extern void penv_slave6_ldm_tbox_count(unsigned long *count);
extern void penv_slave6_accldm_remoterld_init();
extern void penv_slave6_accldm_remoterld_count(unsigned long *count);
extern void penv_slave6_availreq_dcache_prefetch_init();
extern void penv_slave6_availreq_dcache_prefetch_count(unsigned long *count);
extern void penv_slave6_req_dcache_fill_init();
extern void penv_slave6_req_dcache_fill_count(unsigned long *count);
extern void penv_slave6_inst_pipe1_int_init();
extern void penv_slave6_inst_pipe1_int_count(unsigned long *count);
extern void penv_slave6_inst_vector_float_init();
extern void penv_slave6_inst_vector_float_count(unsigned long *count);
extern void penv_slave6_inst_vector_float_adds_init();
extern void penv_slave6_inst_vector_float_adds_count(unsigned long *count);
extern void penv_slave6_req_outsyn_init();
extern void penv_slave6_req_outsyn_count(unsigned long *count);
extern void penv_slave6_req_fence_total_init();
extern void penv_slave6_req_fence_total_count(unsigned long *count);
extern void penv_slave6_inst_buffirstdmarma_0_0_init();
extern void penv_slave6_inst_buffirstdmarma_0_0_count(unsigned long *count);
extern void penv_slave6_req_ldm_ram_read_init();
extern void penv_slave6_req_ldm_ram_read_count(unsigned long *count);
extern void penv_slave6_inst_vector_half_float_adds_init();
extern void penv_slave6_inst_vector_half_float_adds_count(unsigned long *count);
extern void penv_slave6_cyc_launhcnone_buffer_init();
extern void penv_slave6_cyc_launhcnone_buffer_count(unsigned long *count);
extern void penv_slave6_cyc_memb_wait_init();
extern void penv_slave6_cyc_memb_wait_count(unsigned long *count);
extern void penv_slave6_cyc_pipe0_noinst_init();
extern void penv_slave6_cyc_pipe0_noinst_count(unsigned long *count);
extern void penv_slave6_l0ic_bubble_init();
extern void penv_slave6_l0ic_bubble_count(unsigned long *count);
extern void penv_slave6_inst_conflag_init();
extern void penv_slave6_inst_conflag_count(unsigned long *count);
extern void penv_slave6_fail_prejump_forward_init();
extern void penv_slave6_fail_prejump_forward_count(unsigned long *count);
extern void penv_slave6_cyc_dcache_crq_init();
extern void penv_slave6_cyc_dcache_crq_count(unsigned long *count);
extern void penv_slave6_ldm_tbox_init();
extern void penv_slave6_ldm_tbox_count(unsigned long *count);
extern void penv_slave6_accldm_remoterld_init();
extern void penv_slave6_accldm_remoterld_count(unsigned long *count);
extern void penv_slave6_availreq_dcache_prefetch_init();
extern void penv_slave6_availreq_dcache_prefetch_count(unsigned long *count);
extern void penv_slave6_req_dcache_fill_init();
extern void penv_slave6_req_dcache_fill_count(unsigned long *count);
extern void penv_slave6_inst_pipe1_int_init();
extern void penv_slave6_inst_pipe1_int_count(unsigned long *count);
extern void penv_slave6_inst_vector_float_init();
extern void penv_slave6_inst_vector_float_count(unsigned long *count);
extern void penv_slave6_inst_vector_float_adds_init();
extern void penv_slave6_inst_vector_float_adds_count(unsigned long *count);
extern void penv_slave6_req_outsyn_init();
extern void penv_slave6_req_outsyn_count(unsigned long *count);
extern void penv_slave6_req_fence_total_init();
extern void penv_slave6_req_fence_total_count(unsigned long *count);
extern void penv_slave6_inst_buffirstdmarma_0_0_init();
extern void penv_slave6_inst_buffirstdmarma_0_0_count(unsigned long *count);
extern void penv_slave6_req_ldm_ram_read_init();
extern void penv_slave6_req_ldm_ram_read_count(unsigned long *count);
extern void penv_slave6_inst_vector_half_float_adds_init();
extern void penv_slave6_inst_vector_half_float_adds_count(unsigned long *count);
extern void penv_slave7_inst_l0ic_read_init();
extern void penv_slave7_inst_l0ic_read_count(unsigned long *count);
extern void penv_slave7_inst_buffirstdmarma_0_0_init();
extern void penv_slave7_inst_buffirstdmarma_0_0_count(unsigned long *count);
extern void penv_slave7_cyc_instbufferempty_init();
extern void penv_slave7_cyc_instbufferempty_count(unsigned long *count);
extern void penv_slave7_cyc_pipe1_noinst_init();
extern void penv_slave7_cyc_pipe1_noinst_count(unsigned long *count);
extern void penv_slave7_fail_prejump_back_init();
extern void penv_slave7_fail_prejump_back_count(unsigned long *count);
extern void penv_slave7_cyc_rscatter_memacc_unarbitrate_init();
extern void penv_slave7_cyc_rscatter_memacc_unarbitrate_count(unsigned long *count);
extern void penv_slave7_ldm_rmw_wr_init();
extern void penv_slave7_ldm_rmw_wr_count(unsigned long *count);
extern void penv_slave7_accldm_remoterst_init();
extern void penv_slave7_accldm_remoterst_count(unsigned long *count);
extern void penv_slave7_cyc_dcache_crq_init();
extern void penv_slave7_cyc_dcache_crq_count(unsigned long *count);
extern void penv_slave7_req_dcache_evict_init();
extern void penv_slave7_req_dcache_evict_count(unsigned long *count);
extern void penv_slave7_inst_pipe1_memacc_init();
extern void penv_slave7_inst_pipe1_memacc_count(unsigned long *count);
extern void penv_slave7_inst_vector_memacc_init();
extern void penv_slave7_inst_vector_memacc_count(unsigned long *count);
extern void penv_slave7_inst_vector_float_muls_init();
extern void penv_slave7_inst_vector_float_muls_count(unsigned long *count);
extern void penv_slave7_req_wrch_init();
extern void penv_slave7_req_wrch_count(unsigned long *count);
extern void penv_slave7_req_fence_total_wait_init();
extern void penv_slave7_req_fence_total_wait_count(unsigned long *count);
extern void penv_slave7_req_gpr_read_init();
extern void penv_slave7_req_gpr_read_count(unsigned long *count);
extern void penv_slave7_inst_vector_half_float_muls_init();
extern void penv_slave7_inst_vector_half_float_muls_count(unsigned long *count);
extern void penv_slave7_inst_l0ic_read_init();
extern void penv_slave7_inst_l0ic_read_count(unsigned long *count);
extern void penv_slave7_inst_buffirstdmarma_0_0_init();
extern void penv_slave7_inst_buffirstdmarma_0_0_count(unsigned long *count);
extern void penv_slave7_cyc_instbufferempty_init();
extern void penv_slave7_cyc_instbufferempty_count(unsigned long *count);
extern void penv_slave7_cyc_pipe1_noinst_init();
extern void penv_slave7_cyc_pipe1_noinst_count(unsigned long *count);
extern void penv_slave7_fail_prejump_back_init();
extern void penv_slave7_fail_prejump_back_count(unsigned long *count);
extern void penv_slave7_cyc_rscatter_memacc_unarbitrate_init();
extern void penv_slave7_cyc_rscatter_memacc_unarbitrate_count(unsigned long *count);
extern void penv_slave7_ldm_rmw_wr_init();
extern void penv_slave7_ldm_rmw_wr_count(unsigned long *count);
extern void penv_slave7_accldm_remoterst_init();
extern void penv_slave7_accldm_remoterst_count(unsigned long *count);
extern void penv_slave7_cyc_dcache_crq_init();
extern void penv_slave7_cyc_dcache_crq_count(unsigned long *count);
extern void penv_slave7_req_dcache_evict_init();
extern void penv_slave7_req_dcache_evict_count(unsigned long *count);
extern void penv_slave7_inst_pipe1_memacc_init();
extern void penv_slave7_inst_pipe1_memacc_count(unsigned long *count);
extern void penv_slave7_inst_vector_memacc_init();
extern void penv_slave7_inst_vector_memacc_count(unsigned long *count);
extern void penv_slave7_inst_vector_float_muls_init();
extern void penv_slave7_inst_vector_float_muls_count(unsigned long *count);
extern void penv_slave7_req_wrch_init();
extern void penv_slave7_req_wrch_count(unsigned long *count);
extern void penv_slave7_req_fence_total_wait_init();
extern void penv_slave7_req_fence_total_wait_count(unsigned long *count);
extern void penv_slave7_req_gpr_read_init();
extern void penv_slave7_req_gpr_read_count(unsigned long *count);
extern void penv_slave7_inst_vector_half_float_muls_init();
extern void penv_slave7_inst_vector_half_float_muls_count(unsigned long *count);
extern void penv_cg_syn_pcr_cycle_init();
extern void penv_cg_syn_pcr_cycle_count(unsigned long *count);
extern void penv_cg_syn_pcr_l_up_init();
extern void penv_cg_syn_pcr_l_up_count(unsigned long *count);
extern void penv_cg_syn_pcr_l_down_init();
extern void penv_cg_syn_pcr_l_down_count(unsigned long *count);
extern void penv_cg_syn_pcr_s_in_init();
extern void penv_cg_syn_pcr_s_in_count(unsigned long *count);
extern void penv_cg_syn_pcr_s_out_init();
extern void penv_cg_syn_pcr_s_out_count(unsigned long *count);
extern void penv_cg_syn_pcr_n_in_init();
extern void penv_cg_syn_pcr_n_in_count(unsigned long *count);
extern void penv_cg_syn_pcr_n_out_init();
extern void penv_cg_syn_pcr_n_out_count(unsigned long *count);
extern void penv_cg_syn_pcr_w_in_init();
extern void penv_cg_syn_pcr_w_in_count(unsigned long *count);
extern void penv_cg_syn_pcr_w_out_init();
extern void penv_cg_syn_pcr_w_out_count(unsigned long *count);
extern void penv_cg_syn_pcr_e_in_init();
extern void penv_cg_syn_pcr_e_in_count(unsigned long *count);
extern void penv_cg_syn_pcr_e_out_init();
extern void penv_cg_syn_pcr_e_out_count(unsigned long *count);
extern void penv_cg_syn_pcr_l_fwait_init();
extern void penv_cg_syn_pcr_l_fwait_count(unsigned long *count);
extern void penv_cg_syn_pcr_s_fwait_init();
extern void penv_cg_syn_pcr_s_fwait_count(unsigned long *count);
extern void penv_cg_syn_pcr_n_fwait_init();
extern void penv_cg_syn_pcr_n_fwait_count(unsigned long *count);
extern void penv_cg_syn_pcr_w_fwait_init();
extern void penv_cg_syn_pcr_w_fwait_count(unsigned long *count);
extern void penv_cg_syn_pcr_e_fwait_init();
extern void penv_cg_syn_pcr_e_fwait_count(unsigned long *count);
extern void penv_cg_syn_pcr_req_sbox0_init();
extern void penv_cg_syn_pcr_req_sbox0_count(unsigned long *count);
extern void penv_cg_syn_pcr_req_sbox1_init();
extern void penv_cg_syn_pcr_req_sbox1_count(unsigned long *count);
extern void penv_cg_syn_pcr_req_sbox2_init();
extern void penv_cg_syn_pcr_req_sbox2_count(unsigned long *count);
extern void penv_cg_syn_pcr_req_sbox3_init();
extern void penv_cg_syn_pcr_req_sbox3_count(unsigned long *count);
extern void penv_cg_syn_pcr_req_tbox_init();
extern void penv_cg_syn_pcr_req_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_cycle_init();
extern void penv_cg_stn_lpcr0_l0_cycle_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p0up_flit_init();
extern void penv_cg_stn_lpcr0_l0_req_p0up_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_res_p0down_flit_init();
extern void penv_cg_stn_lpcr0_l0_res_p0down_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p0up_pack_init();
extern void penv_cg_stn_lpcr0_l0_req_p0up_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_res_p0down_pack_init();
extern void penv_cg_stn_lpcr0_l0_res_p0down_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_block_res_p0first_init();
extern void penv_cg_stn_lpcr0_l0_block_res_p0first_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p0up_flit_sbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p0up_flit_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p0up_flit_tbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p0up_flit_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p0up_pack_sbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p0up_pack_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p0up_pack_tbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p0up_pack_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1up_flit_init();
extern void penv_cg_stn_lpcr0_l0_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_res_p1up_flit_init();
extern void penv_cg_stn_lpcr0_l0_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1down_flit_init();
extern void penv_cg_stn_lpcr0_l0_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_res_p1down_flit_init();
extern void penv_cg_stn_lpcr0_l0_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1up_pack_init();
extern void penv_cg_stn_lpcr0_l0_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_res_p1up_pack_init();
extern void penv_cg_stn_lpcr0_l0_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1down_pack_init();
extern void penv_cg_stn_lpcr0_l0_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_res_p1down_pack_init();
extern void penv_cg_stn_lpcr0_l0_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_block_req_p1first_init();
extern void penv_cg_stn_lpcr0_l0_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_block_res_p1first_init();
extern void penv_cg_stn_lpcr0_l0_block_res_p1first_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1up_flit_sbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p1up_flit_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1up_flit_tbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p1up_flit_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1up_pack_sbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p1up_pack_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr0_l0_req_p1up_pack_tbox_init();
extern void penv_cg_stn_lpcr0_l0_req_p1up_pack_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_cycle_init();
extern void penv_cg_stn_lpcr1_l1_cycle_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p0up_flit_init();
extern void penv_cg_stn_lpcr1_l1_req_p0up_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_res_p0down_flit_init();
extern void penv_cg_stn_lpcr1_l1_res_p0down_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p0up_pack_init();
extern void penv_cg_stn_lpcr1_l1_req_p0up_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_res_p0down_pack_init();
extern void penv_cg_stn_lpcr1_l1_res_p0down_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_block_res_p0first_init();
extern void penv_cg_stn_lpcr1_l1_block_res_p0first_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p0up_flit_sbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p0up_flit_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p0up_flit_tbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p0up_flit_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p0up_pack_sbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p0up_pack_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p0up_pack_tbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p0up_pack_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1up_flit_init();
extern void penv_cg_stn_lpcr1_l1_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_res_p1up_flit_init();
extern void penv_cg_stn_lpcr1_l1_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1down_flit_init();
extern void penv_cg_stn_lpcr1_l1_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_res_p1down_flit_init();
extern void penv_cg_stn_lpcr1_l1_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1up_pack_init();
extern void penv_cg_stn_lpcr1_l1_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_res_p1up_pack_init();
extern void penv_cg_stn_lpcr1_l1_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1down_pack_init();
extern void penv_cg_stn_lpcr1_l1_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_res_p1down_pack_init();
extern void penv_cg_stn_lpcr1_l1_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_block_req_p1first_init();
extern void penv_cg_stn_lpcr1_l1_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_block_res_p1first_init();
extern void penv_cg_stn_lpcr1_l1_block_res_p1first_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1up_flit_sbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p1up_flit_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1up_flit_tbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p1up_flit_tbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1up_pack_sbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p1up_pack_sbox_count(unsigned long *count);
extern void penv_cg_stn_lpcr1_l1_req_p1up_pack_tbox_init();
extern void penv_cg_stn_lpcr1_l1_req_p1up_pack_tbox_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_cycle_init();
extern void penv_cg_stn_spcr0_s0_cycle_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_res_p0up_flit_init();
extern void penv_cg_stn_spcr0_s0_res_p0up_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_req_p0down_flit_init();
extern void penv_cg_stn_spcr0_s0_req_p0down_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_res_p0up_pack_init();
extern void penv_cg_stn_spcr0_s0_res_p0up_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_req_p0down_pack_init();
extern void penv_cg_stn_spcr0_s0_req_p0down_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_block_res_p0first_init();
extern void penv_cg_stn_spcr0_s0_block_res_p0first_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_req_p1up_flit_init();
extern void penv_cg_stn_spcr0_s0_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_res_p1up_flit_init();
extern void penv_cg_stn_spcr0_s0_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_req_p1down_flit_init();
extern void penv_cg_stn_spcr0_s0_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_res_p1down_flit_init();
extern void penv_cg_stn_spcr0_s0_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_req_p1up_pack_init();
extern void penv_cg_stn_spcr0_s0_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_res_p1up_pack_init();
extern void penv_cg_stn_spcr0_s0_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_req_p1down_pack_init();
extern void penv_cg_stn_spcr0_s0_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_res_p1down_pack_init();
extern void penv_cg_stn_spcr0_s0_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_block_req_p1first_init();
extern void penv_cg_stn_spcr0_s0_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_spcr0_s0_block_res_p1first_init();
extern void penv_cg_stn_spcr0_s0_block_res_p1first_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_cycle_init();
extern void penv_cg_stn_spcr1_s1_cycle_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_res_p0up_flit_init();
extern void penv_cg_stn_spcr1_s1_res_p0up_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_req_p0down_flit_init();
extern void penv_cg_stn_spcr1_s1_req_p0down_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_res_p0up_pack_init();
extern void penv_cg_stn_spcr1_s1_res_p0up_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_req_p0down_pack_init();
extern void penv_cg_stn_spcr1_s1_req_p0down_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_block_res_p0first_init();
extern void penv_cg_stn_spcr1_s1_block_res_p0first_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_req_p1up_flit_init();
extern void penv_cg_stn_spcr1_s1_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_res_p1up_flit_init();
extern void penv_cg_stn_spcr1_s1_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_req_p1down_flit_init();
extern void penv_cg_stn_spcr1_s1_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_res_p1down_flit_init();
extern void penv_cg_stn_spcr1_s1_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_req_p1up_pack_init();
extern void penv_cg_stn_spcr1_s1_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_res_p1up_pack_init();
extern void penv_cg_stn_spcr1_s1_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_req_p1down_pack_init();
extern void penv_cg_stn_spcr1_s1_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_res_p1down_pack_init();
extern void penv_cg_stn_spcr1_s1_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_block_req_p1first_init();
extern void penv_cg_stn_spcr1_s1_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_spcr1_s1_block_res_p1first_init();
extern void penv_cg_stn_spcr1_s1_block_res_p1first_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_cycle_init();
extern void penv_cg_stn_npcr0_n0_cycle_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_req_p0up_flit_init();
extern void penv_cg_stn_npcr0_n0_req_p0up_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_res_p0down_flit_init();
extern void penv_cg_stn_npcr0_n0_res_p0down_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_req_p0up_pack_init();
extern void penv_cg_stn_npcr0_n0_req_p0up_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_res_p0down_pack_init();
extern void penv_cg_stn_npcr0_n0_res_p0down_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_block_req_p0first_init();
extern void penv_cg_stn_npcr0_n0_block_req_p0first_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_req_p1up_flit_init();
extern void penv_cg_stn_npcr0_n0_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_res_p1up_flit_init();
extern void penv_cg_stn_npcr0_n0_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_req_p1down_flit_init();
extern void penv_cg_stn_npcr0_n0_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_res_p1down_flit_init();
extern void penv_cg_stn_npcr0_n0_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_req_p1up_pack_init();
extern void penv_cg_stn_npcr0_n0_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_res_p1up_pack_init();
extern void penv_cg_stn_npcr0_n0_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_req_p1down_pack_init();
extern void penv_cg_stn_npcr0_n0_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_res_p1down_pack_init();
extern void penv_cg_stn_npcr0_n0_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_block_req_p1first_init();
extern void penv_cg_stn_npcr0_n0_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_npcr0_n0_block_res_p1first_init();
extern void penv_cg_stn_npcr0_n0_block_res_p1first_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_cycle_init();
extern void penv_cg_stn_npcr1_n1_cycle_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_req_p0up_flit_init();
extern void penv_cg_stn_npcr1_n1_req_p0up_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_res_p0down_flit_init();
extern void penv_cg_stn_npcr1_n1_res_p0down_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_req_p0up_pack_init();
extern void penv_cg_stn_npcr1_n1_req_p0up_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_res_p0down_pack_init();
extern void penv_cg_stn_npcr1_n1_res_p0down_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_block_req_p0first_init();
extern void penv_cg_stn_npcr1_n1_block_req_p0first_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_req_p1up_flit_init();
extern void penv_cg_stn_npcr1_n1_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_res_p1up_flit_init();
extern void penv_cg_stn_npcr1_n1_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_req_p1down_flit_init();
extern void penv_cg_stn_npcr1_n1_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_res_p1down_flit_init();
extern void penv_cg_stn_npcr1_n1_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_req_p1up_pack_init();
extern void penv_cg_stn_npcr1_n1_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_res_p1up_pack_init();
extern void penv_cg_stn_npcr1_n1_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_req_p1down_pack_init();
extern void penv_cg_stn_npcr1_n1_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_res_p1down_pack_init();
extern void penv_cg_stn_npcr1_n1_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_block_req_p1first_init();
extern void penv_cg_stn_npcr1_n1_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_npcr1_n1_block_res_p1first_init();
extern void penv_cg_stn_npcr1_n1_block_res_p1first_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_cycle_init();
extern void penv_cg_stn_wpcr1_w1_cycle_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_req_p1up_flit_init();
extern void penv_cg_stn_wpcr1_w1_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_res_p1up_flit_init();
extern void penv_cg_stn_wpcr1_w1_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_req_p1down_flit_init();
extern void penv_cg_stn_wpcr1_w1_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_res_p1down_flit_init();
extern void penv_cg_stn_wpcr1_w1_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_req_p1up_pack_init();
extern void penv_cg_stn_wpcr1_w1_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_res_p1up_pack_init();
extern void penv_cg_stn_wpcr1_w1_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_req_p1down_pack_init();
extern void penv_cg_stn_wpcr1_w1_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_res_p1down_pack_init();
extern void penv_cg_stn_wpcr1_w1_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_block_req_p1first_init();
extern void penv_cg_stn_wpcr1_w1_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_wpcr1_w1_block_res_p1first_init();
extern void penv_cg_stn_wpcr1_w1_block_res_p1first_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_cycle_init();
extern void penv_cg_stn_epcr1_e1_cycle_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_req_p1up_flit_init();
extern void penv_cg_stn_epcr1_e1_req_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_res_p1up_flit_init();
extern void penv_cg_stn_epcr1_e1_res_p1up_flit_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_req_p1down_flit_init();
extern void penv_cg_stn_epcr1_e1_req_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_res_p1down_flit_init();
extern void penv_cg_stn_epcr1_e1_res_p1down_flit_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_req_p1up_pack_init();
extern void penv_cg_stn_epcr1_e1_req_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_res_p1up_pack_init();
extern void penv_cg_stn_epcr1_e1_res_p1up_pack_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_req_p1down_pack_init();
extern void penv_cg_stn_epcr1_e1_req_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_res_p1down_pack_init();
extern void penv_cg_stn_epcr1_e1_res_p1down_pack_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_block_req_p1first_init();
extern void penv_cg_stn_epcr1_e1_block_req_p1first_count(unsigned long *count);
extern void penv_cg_stn_epcr1_e1_block_res_p1first_init();
extern void penv_cg_stn_epcr1_e1_block_res_p1first_count(unsigned long *count);
extern void penv_cg_tbox0_cycle_init();
extern void penv_cg_tbox0_cycle_count(unsigned long *count);
extern void penv_cg_tbox1_desc_dma_rma_init();
extern void penv_cg_tbox1_desc_dma_rma_count(unsigned long *count);
extern void penv_cg_tbox1_desc_dma_get_init();
extern void penv_cg_tbox1_desc_dma_get_count(unsigned long *count);
extern void penv_cg_tbox1_desc_dma_put_init();
extern void penv_cg_tbox1_desc_dma_put_count(unsigned long *count);
extern void penv_cg_tbox1_desc_rma_get_init();
extern void penv_cg_tbox1_desc_rma_get_count(unsigned long *count);
extern void penv_cg_tbox1_desc_rma_put_init();
extern void penv_cg_tbox1_desc_rma_put_count(unsigned long *count);
extern void penv_cg_tbox1_cnt_reqans_mbox0_init();
extern void penv_cg_tbox1_cnt_reqans_mbox0_count(unsigned long *count);
extern void penv_cg_tbox1_cnt_reqans_mbox1_init();
extern void penv_cg_tbox1_cnt_reqans_mbox1_count(unsigned long *count);
extern void penv_cg_tbox1_cnt_reqans_mbox2_init();
extern void penv_cg_tbox1_cnt_reqans_mbox2_count(unsigned long *count);
extern void penv_cg_tbox1_cnt_reqans_mbox3_init();
extern void penv_cg_tbox1_cnt_reqans_mbox3_count(unsigned long *count);
extern void penv_cg_tbox1_req_mbox0_read32_init();
extern void penv_cg_tbox1_req_mbox0_read32_count(unsigned long *count);
extern void penv_cg_tbox1_req_mbox0_read64_init();
extern void penv_cg_tbox1_req_mbox0_read64_count(unsigned long *count);
extern void penv_cg_tbox1_cyc_mbox0_cannotsend_availreq_init();
extern void penv_cg_tbox1_cyc_mbox0_cannotsend_availreq_count(unsigned long *count);
extern void penv_cg_tbox1_cnt_reqw_mbox0_init();
extern void penv_cg_tbox1_cnt_reqw_mbox0_count(unsigned long *count);
extern void penv_cg_tbox1_cyc_tbox_eng0_sendportbusy_init();
extern void penv_cg_tbox1_cyc_tbox_eng0_sendportbusy_count(unsigned long *count);
extern void penv_cg_tbox1_req_tbox_eng0_get_init();
extern void penv_cg_tbox1_req_tbox_eng0_get_count(unsigned long *count);
extern void penv_cg_tbox1_cyc_tbox_eng0_rdbuf_init();
extern void penv_cg_tbox1_cyc_tbox_eng0_rdbuf_count(unsigned long *count);
extern void penv_cg_tbox1_cyc_tbox_eng0ldm_divp_avail_init();
extern void penv_cg_tbox1_cyc_tbox_eng0ldm_divp_avail_count(unsigned long *count);
extern void penv_cg_tbox1_req_tbox_eng1_get_init();
extern void penv_cg_tbox1_req_tbox_eng1_get_count(unsigned long *count);
extern void penv_cg_tbox1_cyc_tbox_eng1_rdbuf_init();
extern void penv_cg_tbox1_cyc_tbox_eng1_rdbuf_count(unsigned long *count);
extern void penv_cg_tbox1_req_tbox_eng1_rev1flit_init();
extern void penv_cg_tbox1_req_tbox_eng1_rev1flit_count(unsigned long *count);
extern void penv_cg_tbox1_cyc_tbox_eng1_wrbuf_init();
extern void penv_cg_tbox1_cyc_tbox_eng1_wrbuf_count(unsigned long *count);
extern void penv_cg_tbox1_cyc_tbox_eng1ldm_divp_avail_init();
extern void penv_cg_tbox1_cyc_tbox_eng1ldm_divp_avail_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_req_dma_rma_init();
extern void penv_cg_tbox2_cyc_req_dma_rma_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_req_dma_get_init();
extern void penv_cg_tbox2_cyc_req_dma_get_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_req_dma_put_init();
extern void penv_cg_tbox2_cyc_req_dma_put_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_req_rma_get_init();
extern void penv_cg_tbox2_cyc_req_rma_get_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_req_rma_put_init();
extern void penv_cg_tbox2_cyc_req_rma_put_count(unsigned long *count);
extern void penv_cg_tbox2_desc_dma_put_init();
extern void penv_cg_tbox2_desc_dma_put_count(unsigned long *count);
extern void penv_cg_tbox2_req_read32_mbox0_init();
extern void penv_cg_tbox2_req_read32_mbox0_count(unsigned long *count);
extern void penv_cg_tbox2_req_read32_mbox1_init();
extern void penv_cg_tbox2_req_read32_mbox1_count(unsigned long *count);
extern void penv_cg_tbox2_req_read32_mbox2_init();
extern void penv_cg_tbox2_req_read32_mbox2_count(unsigned long *count);
extern void penv_cg_tbox2_req_read32_mbox3_init();
extern void penv_cg_tbox2_req_read32_mbox3_count(unsigned long *count);
extern void penv_cg_tbox2_cnt_reqans_mbox1_init();
extern void penv_cg_tbox2_cnt_reqans_mbox1_count(unsigned long *count);
extern void penv_cg_tbox2_req_mbox1_read32_init();
extern void penv_cg_tbox2_req_mbox1_read32_count(unsigned long *count);
extern void penv_cg_tbox2_req_mbox1_read64_init();
extern void penv_cg_tbox2_req_mbox1_read64_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_mbox1_cannotsend_availreq_init();
extern void penv_cg_tbox2_cyc_mbox1_cannotsend_availreq_count(unsigned long *count);
extern void penv_cg_tbox2_cnt_reqw_mbox1_init();
extern void penv_cg_tbox2_cnt_reqw_mbox1_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_tbox_eng0_revportbusy_init();
extern void penv_cg_tbox2_cyc_tbox_eng0_revportbusy_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_tbox_eng0_rdbuf_cannotprocess_init();
extern void penv_cg_tbox2_cyc_tbox_eng0_rdbuf_cannotprocess_count(unsigned long *count);
extern void penv_cg_tbox2_req_tbox_eng0ldm_divp_init();
extern void penv_cg_tbox2_req_tbox_eng0ldm_divp_count(unsigned long *count);
extern void penv_cg_tbox2_req_tbox_eng1_send_rma_put_bc_init();
extern void penv_cg_tbox2_req_tbox_eng1_send_rma_put_bc_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_tbox_eng1_rdbuf_cannotprocess_init();
extern void penv_cg_tbox2_cyc_tbox_eng1_rdbuf_cannotprocess_count(unsigned long *count);
extern void penv_cg_tbox2_req_tbox_eng1_rev2flit_init();
extern void penv_cg_tbox2_req_tbox_eng1_rev2flit_count(unsigned long *count);
extern void penv_cg_tbox2_cyc_tbox_eng1_wrbuf_cannotprocess_init();
extern void penv_cg_tbox2_cyc_tbox_eng1_wrbuf_cannotprocess_count(unsigned long *count);
extern void penv_cg_tbox2_req_tbox_eng1ldm_divp_init();
extern void penv_cg_tbox2_req_tbox_eng1ldm_divp_count(unsigned long *count);
extern void penv_cg_tbox3_desc_rma_get_init();
extern void penv_cg_tbox3_desc_rma_get_count(unsigned long *count);
extern void penv_cg_tbox3_req_read64_mbox0_init();
extern void penv_cg_tbox3_req_read64_mbox0_count(unsigned long *count);
extern void penv_cg_tbox3_req_read64_mbox1_init();
extern void penv_cg_tbox3_req_read64_mbox1_count(unsigned long *count);
extern void penv_cg_tbox3_req_read64_mbox2_init();
extern void penv_cg_tbox3_req_read64_mbox2_count(unsigned long *count);
extern void penv_cg_tbox3_req_read64_mbox3_init();
extern void penv_cg_tbox3_req_read64_mbox3_count(unsigned long *count);
extern void penv_cg_tbox3_cnt_reqans_mbox2_init();
extern void penv_cg_tbox3_cnt_reqans_mbox2_count(unsigned long *count);
extern void penv_cg_tbox3_req_mbox2_read32_init();
extern void penv_cg_tbox3_req_mbox2_read32_count(unsigned long *count);
extern void penv_cg_tbox3_req_mbox2_read64_init();
extern void penv_cg_tbox3_req_mbox2_read64_count(unsigned long *count);
extern void penv_cg_tbox3_cyc_mbox2_cannotsend_availreq_init();
extern void penv_cg_tbox3_cyc_mbox2_cannotsend_availreq_count(unsigned long *count);
extern void penv_cg_tbox3_cnt_reqw_mbox2_init();
extern void penv_cg_tbox3_cnt_reqw_mbox2_count(unsigned long *count);
extern void penv_cg_tbox3_cyc_tbox_eng1_sendportbusy_init();
extern void penv_cg_tbox3_cyc_tbox_eng1_sendportbusy_count(unsigned long *count);
extern void penv_cg_tbox3_req_tbox_eng0_send3flit_init();
extern void penv_cg_tbox3_req_tbox_eng0_send3flit_count(unsigned long *count);
extern void penv_cg_tbox3_cyc_tbox_eng0_wrbuf_res_init();
extern void penv_cg_tbox3_cyc_tbox_eng0_wrbuf_res_count(unsigned long *count);
extern void penv_cg_tbox3_req_tbox_eng0ldm_divp_bacst_init();
extern void penv_cg_tbox3_req_tbox_eng0ldm_divp_bacst_count(unsigned long *count);
extern void penv_cg_tbox3_req_tbox_eng1_send3flit_init();
extern void penv_cg_tbox3_req_tbox_eng1_send3flit_count(unsigned long *count);
extern void penv_cg_tbox3_cyc_tbox_eng1_rdbuf_res_init();
extern void penv_cg_tbox3_cyc_tbox_eng1_rdbuf_res_count(unsigned long *count);
extern void penv_cg_tbox3_req_tbox_eng1_rev3flit_init();
extern void penv_cg_tbox3_req_tbox_eng1_rev3flit_count(unsigned long *count);
extern void penv_cg_tbox3_cyc_tbox_eng1_wrbuf_res_init();
extern void penv_cg_tbox3_cyc_tbox_eng1_wrbuf_res_count(unsigned long *count);
extern void penv_cg_tbox3_req_tbox_eng1ldm_divp_bacst_init();
extern void penv_cg_tbox3_req_tbox_eng1ldm_divp_bacst_count(unsigned long *count);
extern void penv_cg_tbox4_desc_rma_put_init();
extern void penv_cg_tbox4_desc_rma_put_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_inavail_req_mbox0_init();
extern void penv_cg_tbox4_cyc_inavail_req_mbox0_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_inavail_req_mbox1_init();
extern void penv_cg_tbox4_cyc_inavail_req_mbox1_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_inavail_req_mbox2_init();
extern void penv_cg_tbox4_cyc_inavail_req_mbox2_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_inavail_req_mbox3_init();
extern void penv_cg_tbox4_cyc_inavail_req_mbox3_count(unsigned long *count);
extern void penv_cg_tbox4_cnt_reqans_mbox3_init();
extern void penv_cg_tbox4_cnt_reqans_mbox3_count(unsigned long *count);
extern void penv_cg_tbox4_req_mbox3_read32_init();
extern void penv_cg_tbox4_req_mbox3_read32_count(unsigned long *count);
extern void penv_cg_tbox4_req_mbox3_read64_init();
extern void penv_cg_tbox4_req_mbox3_read64_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_mbox3_cannotsend_availreq_init();
extern void penv_cg_tbox4_cyc_mbox3_cannotsend_availreq_count(unsigned long *count);
extern void penv_cg_tbox4_cnt_reqw_mbox3_init();
extern void penv_cg_tbox4_cnt_reqw_mbox3_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_tbox_eng1_revportbusy_init();
extern void penv_cg_tbox4_cyc_tbox_eng1_revportbusy_count(unsigned long *count);
extern void penv_cg_tbox4_req_tbox_eng0_send5flit_init();
extern void penv_cg_tbox4_req_tbox_eng0_send5flit_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_tbox_eng0_wrbuf_res_cannotprocess_init();
extern void penv_cg_tbox4_cyc_tbox_eng0_wrbuf_res_cannotprocess_count(unsigned long *count);
extern void penv_cg_tbox4_req_tbox_eng0ldm_divp_bacst_avail_haltothre_init();
extern void penv_cg_tbox4_req_tbox_eng0ldm_divp_bacst_avail_haltothre_count(unsigned long *count);
extern void penv_cg_tbox4_req_tbox_eng1_send5flit_init();
extern void penv_cg_tbox4_req_tbox_eng1_send5flit_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_tbox_eng1_rdbuf_res_cannotprocess_init();
extern void penv_cg_tbox4_cyc_tbox_eng1_rdbuf_res_cannotprocess_count(unsigned long *count);
extern void penv_cg_tbox4_req_tbox_eng1_rev5flit_init();
extern void penv_cg_tbox4_req_tbox_eng1_rev5flit_count(unsigned long *count);
extern void penv_cg_tbox4_cyc_tbox_eng1_wrbuf_res_cannotprocess_init();
extern void penv_cg_tbox4_cyc_tbox_eng1_wrbuf_res_cannotprocess_count(unsigned long *count);
extern void penv_cg_tbox4_req_tbox_eng1ldm_divp_bacst_avail_haltothre_init();
extern void penv_cg_tbox4_req_tbox_eng1ldm_divp_bacst_avail_haltothre_count(unsigned long *count);
extern void penv_cg_tbox5_cnt_reqw_mbox0_init();
extern void penv_cg_tbox5_cnt_reqw_mbox0_count(unsigned long *count);
extern void penv_cg_tbox5_cnt_reqw_mbox1_init();
extern void penv_cg_tbox5_cnt_reqw_mbox1_count(unsigned long *count);
extern void penv_cg_tbox5_cnt_reqw_mbox2_init();
extern void penv_cg_tbox5_cnt_reqw_mbox2_count(unsigned long *count);
extern void penv_cg_tbox5_cnt_reqw_mbox3_init();
extern void penv_cg_tbox5_cnt_reqw_mbox3_count(unsigned long *count);
extern void penv_cg_tbox5_req_tbox_eng0_sendport_init();
extern void penv_cg_tbox5_req_tbox_eng0_sendport_count(unsigned long *count);
extern void penv_cg_tbox5_cyc_tbox_eng0_sendportbusy_init();
extern void penv_cg_tbox5_cyc_tbox_eng0_sendportbusy_count(unsigned long *count);
extern void penv_cg_tbox5_req_tbox_eng0_rev5flit_init();
extern void penv_cg_tbox5_req_tbox_eng0_rev5flit_count(unsigned long *count);
extern void penv_cg_tbox5_cyc_tbox_eng0_revportbusy_init();
extern void penv_cg_tbox5_cyc_tbox_eng0_revportbusy_count(unsigned long *count);
extern void penv_cg_tbox5_conflict_tbox_eng0tbox_rdbuf_write_init();
extern void penv_cg_tbox5_conflict_tbox_eng0tbox_rdbuf_write_count(unsigned long *count);
extern void penv_cg_tbox5_req_tbox_eng1_sendport_init();
extern void penv_cg_tbox5_req_tbox_eng1_sendport_count(unsigned long *count);
extern void penv_cg_tbox5_cyc_tbox_eng1_sendportbusy_init();
extern void penv_cg_tbox5_cyc_tbox_eng1_sendportbusy_count(unsigned long *count);
extern void penv_cg_tbox5_req_tbox_eng1_rev5flit_init();
extern void penv_cg_tbox5_req_tbox_eng1_rev5flit_count(unsigned long *count);
extern void penv_cg_tbox5_cyc_tbox_eng1_revportbusy_init();
extern void penv_cg_tbox5_cyc_tbox_eng1_revportbusy_count(unsigned long *count);
extern void penv_cg_tbox5_conflict_tbox_eng1tbox_rdbuf_write_init();
extern void penv_cg_tbox5_conflict_tbox_eng1tbox_rdbuf_write_count(unsigned long *count);
extern void penv_cg_tbox6_total_trans_init();
extern void penv_cg_tbox6_total_trans_count(unsigned long *count);
extern void penv_cg_tbox6_total_dma_get_init();
extern void penv_cg_tbox6_total_dma_get_count(unsigned long *count);
extern void penv_cg_tbox6_total_dma_put_init();
extern void penv_cg_tbox6_total_dma_put_count(unsigned long *count);
extern void penv_cg_tbox6_total_rma_get_init();
extern void penv_cg_tbox6_total_rma_get_count(unsigned long *count);
extern void penv_cg_tbox6_total_rma_put_init();
extern void penv_cg_tbox6_total_rma_put_count(unsigned long *count);
extern void penv_cg_scmt0_req_io_init();
extern void penv_cg_scmt0_req_io_count(unsigned long *count);
extern void penv_cg_scmt0_res_io_init();
extern void penv_cg_scmt0_res_io_count(unsigned long *count);
extern void penv_cg_scmt0_req_scm_io_init();
extern void penv_cg_scmt0_req_scm_io_count(unsigned long *count);
extern void penv_cg_scmt0_req_bcast_scm_io_init();
extern void penv_cg_scmt0_req_bcast_scm_io_count(unsigned long *count);
extern void penv_cg_scmt0_req_bcast_slave_io_init();
extern void penv_cg_scmt0_req_bcast_slave_io_count(unsigned long *count);
extern void penv_cg_scmt1_req_io_init();
extern void penv_cg_scmt1_req_io_count(unsigned long *count);
extern void penv_cg_scmt1_res_io_init();
extern void penv_cg_scmt1_res_io_count(unsigned long *count);
extern void penv_cg_scmt1_req_scm_io_init();
extern void penv_cg_scmt1_req_scm_io_count(unsigned long *count);
extern void penv_cg_scmt1_req_bcast_scm_io_init();
extern void penv_cg_scmt1_req_bcast_scm_io_count(unsigned long *count);
extern void penv_cg_scmt1_req_bcast_slave_io_init();
extern void penv_cg_scmt1_req_bcast_slave_io_count(unsigned long *count);
extern void penv_cg_paiu0_cycle_init();
extern void penv_cg_paiu0_cycle_count(unsigned long *count);
extern void penv_cg_paiu0_flit_req_stn0_init();
extern void penv_cg_paiu0_flit_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu0_pack_req_stn0_init();
extern void penv_cg_paiu0_pack_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu0_pack_intrer_req_stn0_init();
extern void penv_cg_paiu0_pack_intrer_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu0_pack_bcast_stn0_init();
extern void penv_cg_paiu0_pack_bcast_stn0_count(unsigned long *count);
extern void penv_cg_paiu0_pack_dma_get_stn0_init();
extern void penv_cg_paiu0_pack_dma_get_stn0_count(unsigned long *count);
extern void penv_cg_paiu0_pack_res_sendsyn_init();
extern void penv_cg_paiu0_pack_res_sendsyn_count(unsigned long *count);
extern void penv_cg_paiu0_flit_req_asynsend_init();
extern void penv_cg_paiu0_flit_req_asynsend_count(unsigned long *count);
extern void penv_cg_paiu0_flit_res_asynrev_init();
extern void penv_cg_paiu0_flit_res_asynrev_count(unsigned long *count);
extern void penv_cg_paiu0_pack_req_asynsend_init();
extern void penv_cg_paiu0_pack_req_asynsend_count(unsigned long *count);
extern void penv_cg_paiu0_pack_res_asynrev_init();
extern void penv_cg_paiu0_pack_res_asynrev_count(unsigned long *count);
extern void penv_cg_paiu0_block_asynsendfirst_init();
extern void penv_cg_paiu0_block_asynsendfirst_count(unsigned long *count);
extern void penv_cg_paiu0_block_asynrevfirst_init();
extern void penv_cg_paiu0_block_asynrevfirst_count(unsigned long *count);
extern void penv_cg_paiu0_req_memacc_atom_init();
extern void penv_cg_paiu0_req_memacc_atom_count(unsigned long *count);
extern void penv_cg_paiu1_cycle_init();
extern void penv_cg_paiu1_cycle_count(unsigned long *count);
extern void penv_cg_paiu1_flit_req_stn0_init();
extern void penv_cg_paiu1_flit_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu1_pack_req_stn0_init();
extern void penv_cg_paiu1_pack_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu1_pack_intrer_req_stn0_init();
extern void penv_cg_paiu1_pack_intrer_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu1_pack_bcast_stn0_init();
extern void penv_cg_paiu1_pack_bcast_stn0_count(unsigned long *count);
extern void penv_cg_paiu1_pack_dma_get_stn0_init();
extern void penv_cg_paiu1_pack_dma_get_stn0_count(unsigned long *count);
extern void penv_cg_paiu1_pack_res_sendsyn_init();
extern void penv_cg_paiu1_pack_res_sendsyn_count(unsigned long *count);
extern void penv_cg_paiu1_flit_req_asynsend_init();
extern void penv_cg_paiu1_flit_req_asynsend_count(unsigned long *count);
extern void penv_cg_paiu1_flit_res_asynrev_init();
extern void penv_cg_paiu1_flit_res_asynrev_count(unsigned long *count);
extern void penv_cg_paiu1_pack_req_asynsend_init();
extern void penv_cg_paiu1_pack_req_asynsend_count(unsigned long *count);
extern void penv_cg_paiu1_pack_res_asynrev_init();
extern void penv_cg_paiu1_pack_res_asynrev_count(unsigned long *count);
extern void penv_cg_paiu1_block_asynsendfirst_init();
extern void penv_cg_paiu1_block_asynsendfirst_count(unsigned long *count);
extern void penv_cg_paiu1_block_asynrevfirst_init();
extern void penv_cg_paiu1_block_asynrevfirst_count(unsigned long *count);
extern void penv_cg_paiu1_req_memacc_atom_init();
extern void penv_cg_paiu1_req_memacc_atom_count(unsigned long *count);
extern void penv_cg_paiu2_cycle_init();
extern void penv_cg_paiu2_cycle_count(unsigned long *count);
extern void penv_cg_paiu2_flit_req_stn0_init();
extern void penv_cg_paiu2_flit_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu2_pack_req_stn0_init();
extern void penv_cg_paiu2_pack_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu2_pack_intrer_req_stn0_init();
extern void penv_cg_paiu2_pack_intrer_req_stn0_count(unsigned long *count);
extern void penv_cg_paiu2_pack_bcast_stn0_init();
extern void penv_cg_paiu2_pack_bcast_stn0_count(unsigned long *count);
extern void penv_cg_paiu2_pack_dma_get_stn0_init();
extern void penv_cg_paiu2_pack_dma_get_stn0_count(unsigned long *count);
extern void penv_cg_paiu2_pack_res_sendsyn_init();
extern void penv_cg_paiu2_pack_res_sendsyn_count(unsigned long *count);
extern void penv_cg_paiu2_flit_req_asynsend_init();
extern void penv_cg_paiu2_flit_req_asynsend_count(unsigned long *count);
extern void penv_cg_paiu2_flit_res_asynrev_init();
extern void penv_cg_paiu2_flit_res_asynrev_count(unsigned long *count);
extern void penv_cg_paiu2_pack_req_asynsend_init();
extern void penv_cg_paiu2_pack_req_asynsend_count(unsigned long *count);
extern void penv_cg_paiu2_pack_res_asynrev_init();
extern void penv_cg_paiu2_pack_res_asynrev_count(unsigned long *count);
extern void penv_cg_paiu2_block_asynsendfirst_init();
extern void penv_cg_paiu2_block_asynsendfirst_count(unsigned long *count);
extern void penv_cg_paiu2_block_asynrevfirst_init();
extern void penv_cg_paiu2_block_asynrevfirst_count(unsigned long *count);
extern void penv_cg_paiu2_req_memacc_atom_init();
extern void penv_cg_paiu2_req_memacc_atom_count(unsigned long *count);
extern void penv_mc_uai_perf68event_ch0_w8b_init();
extern void penv_mc_uai_perf68event_ch0_w8b_count(unsigned long *count);
extern void penv_mc_uai_perf69event_ch0_rw8b_init();
extern void penv_mc_uai_perf69event_ch0_rw8b_count(unsigned long *count);
extern void penv_mc_uai_perf70event_ch0_w4b_init();
extern void penv_mc_uai_perf70event_ch0_w4b_count(unsigned long *count);
extern void penv_mc_uai_perf71event_ch0_wp4b_init();
extern void penv_mc_uai_perf71event_ch0_wp4b_count(unsigned long *count);
extern void penv_mc_uai_perf72event_ch0_w2b_init();
extern void penv_mc_uai_perf72event_ch0_w2b_count(unsigned long *count);
extern void penv_mc_uai_perf73event_ch0_w1b_init();
extern void penv_mc_uai_perf73event_ch0_w1b_count(unsigned long *count);
extern void penv_mc_uai_perf74event_ch0_r8b_init();
extern void penv_mc_uai_perf74event_ch0_r8b_count(unsigned long *count);
extern void penv_mc_uai_perf75event_ch0_r4b_init();
extern void penv_mc_uai_perf75event_ch0_r4b_count(unsigned long *count);
extern void penv_mc_uai_perf76event_ch0_r2b_init();
extern void penv_mc_uai_perf76event_ch0_r2b_count(unsigned long *count);
extern void penv_mc_uai_perf77event_ch0_r1b_init();
extern void penv_mc_uai_perf77event_ch0_r1b_count(unsigned long *count);
extern void penv_mc_uai_perf78event_ch0_atom_init();
extern void penv_mc_uai_perf78event_ch0_atom_count(unsigned long *count);
extern void penv_mc_uai_perf79event_ch0_clc_init();
extern void penv_mc_uai_perf79event_ch0_clc_count(unsigned long *count);
extern void penv_mc_uai_perf79event_mc_cycle_init();
extern void penv_mc_uai_perf79event_mc_cycle_count(unsigned long *count);
extern void penv_mc_uai_perf80event_ch1_w8b_init();
extern void penv_mc_uai_perf80event_ch1_w8b_count(unsigned long *count);
extern void penv_mc_uai_perf81event_ch1_rw8b_init();
extern void penv_mc_uai_perf81event_ch1_rw8b_count(unsigned long *count);
extern void penv_mc_uai_perf82event_ch1_w4b_init();
extern void penv_mc_uai_perf82event_ch1_w4b_count(unsigned long *count);
extern void penv_mc_uai_perf83event_ch1_wp4b_init();
extern void penv_mc_uai_perf83event_ch1_wp4b_count(unsigned long *count);
extern void penv_mc_uai_perf84event_ch1_w2b_init();
extern void penv_mc_uai_perf84event_ch1_w2b_count(unsigned long *count);
extern void penv_mc_uai_perf85event_ch1_w1b_init();
extern void penv_mc_uai_perf85event_ch1_w1b_count(unsigned long *count);
extern void penv_mc_uai_perf86event_ch1_r8b_init();
extern void penv_mc_uai_perf86event_ch1_r8b_count(unsigned long *count);
extern void penv_mc_uai_perf87event_ch1_r4b_init();
extern void penv_mc_uai_perf87event_ch1_r4b_count(unsigned long *count);
extern void penv_mc_uai_perf88event_ch1_r2b_init();
extern void penv_mc_uai_perf88event_ch1_r2b_count(unsigned long *count);
extern void penv_mc_uai_perf89event_ch1_r1b_init();
extern void penv_mc_uai_perf89event_ch1_r1b_count(unsigned long *count);
extern void penv_mc_uai_perf90event_ch1_atom_init();
extern void penv_mc_uai_perf90event_ch1_atom_count(unsigned long *count);
extern void penv_mc_uai_perf91event_ch1_clc_init();
extern void penv_mc_uai_perf91event_ch1_clc_count(unsigned long *count);
extern void penv_mc_tran_perf85event_cch1_act_init();
extern void penv_mc_tran_perf85event_cch1_act_count(unsigned long *count);
extern void penv_mc_tran_perf86event_cch0_act_init();
extern void penv_mc_tran_perf86event_cch0_act_count(unsigned long *count);
extern void penv_mc_tran_perf87event_cch1_rd_init();
extern void penv_mc_tran_perf87event_cch1_rd_count(unsigned long *count);
extern void penv_mc_tran_perf88event_cch0_rd_init();
extern void penv_mc_tran_perf88event_cch0_rd_count(unsigned long *count);
extern void penv_mc_tran_perf89event_cch1_wr_init();
extern void penv_mc_tran_perf89event_cch1_wr_count(unsigned long *count);
extern void penv_mc_tran_perf90event_cch0_wr_init();
extern void penv_mc_tran_perf90event_cch0_wr_count(unsigned long *count);
extern void penv_mc_tran_perf91event_cch1_pre_init();
extern void penv_mc_tran_perf91event_cch1_pre_count(unsigned long *count);
extern void penv_mc_tran_perf92event_cch0_pre_init();
extern void penv_mc_tran_perf92event_cch0_pre_count(unsigned long *count);
extern void penv_mc_tran_perf93event_cch1_dram_init();
extern void penv_mc_tran_perf93event_cch1_dram_count(unsigned long *count);
extern void penv_mc_tran_perf94event_cch0_dram_init();
extern void penv_mc_tran_perf94event_cch0_dram_count(unsigned long *count);
extern void penv_mc_tran_perf95event_cch0_bank0_init();
extern void penv_mc_tran_perf95event_cch0_bank0_count(unsigned long *count);
extern void penv_mc_tran_perf96event_cch0_bank1_init();
extern void penv_mc_tran_perf96event_cch0_bank1_count(unsigned long *count);
extern void penv_mc_tran_perf97event_cch0_bank2_init();
extern void penv_mc_tran_perf97event_cch0_bank2_count(unsigned long *count);
extern void penv_mc_tran_perf98event_cch0_bank3_init();
extern void penv_mc_tran_perf98event_cch0_bank3_count(unsigned long *count);
extern void penv_mc_tran_perf99event_cch0_bank4_init();
extern void penv_mc_tran_perf99event_cch0_bank4_count(unsigned long *count);
extern void penv_mc_tran_perf100event_cch0_bank5_init();
extern void penv_mc_tran_perf100event_cch0_bank5_count(unsigned long *count);
extern void penv_mc_tran_perf101event_cch0_bank6_init();
extern void penv_mc_tran_perf101event_cch0_bank6_count(unsigned long *count);
extern void penv_mc_tran_perf102event_cch0_bank7_init();
extern void penv_mc_tran_perf102event_cch0_bank7_count(unsigned long *count);
extern void penv_mc_tran_perf103event_cch0_bank8_init();
extern void penv_mc_tran_perf103event_cch0_bank8_count(unsigned long *count);
extern void penv_mc_tran_perf104event_cch0_bank9_init();
extern void penv_mc_tran_perf104event_cch0_bank9_count(unsigned long *count);
extern void penv_mc_tran_perf105event_cch0_bank10_init();
extern void penv_mc_tran_perf105event_cch0_bank10_count(unsigned long *count);
extern void penv_mc_tran_perf106event_cch0_bank11_init();
extern void penv_mc_tran_perf106event_cch0_bank11_count(unsigned long *count);
extern void penv_mc_tran_perf107event_cch0_bank12_init();
extern void penv_mc_tran_perf107event_cch0_bank12_count(unsigned long *count);
extern void penv_mc_tran_perf108event_cch0_bank13_init();
extern void penv_mc_tran_perf108event_cch0_bank13_count(unsigned long *count);
extern void penv_mc_tran_perf109event_cch0_bank14_init();
extern void penv_mc_tran_perf109event_cch0_bank14_count(unsigned long *count);
extern void penv_mc_tran_perf110event_cch0_bank15_init();
extern void penv_mc_tran_perf110event_cch0_bank15_count(unsigned long *count);
extern void penv_mc_tran_perf111event_cch1_bank0_init();
extern void penv_mc_tran_perf111event_cch1_bank0_count(unsigned long *count);
extern void penv_mc_tran_perf112event_cch1_bank1_init();
extern void penv_mc_tran_perf112event_cch1_bank1_count(unsigned long *count);
extern void penv_mc_tran_perf113event_cch1_bank2_init();
extern void penv_mc_tran_perf113event_cch1_bank2_count(unsigned long *count);
extern void penv_mc_tran_perf114event_cch1_bank3_init();
extern void penv_mc_tran_perf114event_cch1_bank3_count(unsigned long *count);
extern void penv_mc_tran_perf115event_cch1_bank4_init();
extern void penv_mc_tran_perf115event_cch1_bank4_count(unsigned long *count);
extern void penv_mc_tran_perf116event_cch1_bank5_init();
extern void penv_mc_tran_perf116event_cch1_bank5_count(unsigned long *count);
extern void penv_mc_tran_perf117event_cch1_bank6_init();
extern void penv_mc_tran_perf117event_cch1_bank6_count(unsigned long *count);
extern void penv_mc_tran_perf118event_cch1_bank7_init();
extern void penv_mc_tran_perf118event_cch1_bank7_count(unsigned long *count);
extern void penv_mc_tran_perf119event_cch1_bank8_init();
extern void penv_mc_tran_perf119event_cch1_bank8_count(unsigned long *count);
extern void penv_mc_tran_perf120event_cch1_bank9_init();
extern void penv_mc_tran_perf120event_cch1_bank9_count(unsigned long *count);
extern void penv_mc_tran_perf121event_cch1_bank10_init();
extern void penv_mc_tran_perf121event_cch1_bank10_count(unsigned long *count);
extern void penv_mc_tran_perf122event_cch1_bank11_init();
extern void penv_mc_tran_perf122event_cch1_bank11_count(unsigned long *count);
extern void penv_mc_tran_perf123event_cch1_bank12_init();
extern void penv_mc_tran_perf123event_cch1_bank12_count(unsigned long *count);
extern void penv_mc_tran_perf124event_cch1_bank13_init();
extern void penv_mc_tran_perf124event_cch1_bank13_count(unsigned long *count);
extern void penv_mc_tran_perf125event_cch1_bank14_init();
extern void penv_mc_tran_perf125event_cch1_bank14_count(unsigned long *count);
extern void penv_mc_tran_perf126event_cch1_bank15_init();
extern void penv_mc_tran_perf126event_cch1_bank15_count(unsigned long *count);
extern void penv_mc_dch0_perf64event_dch0_rd_valid_init();
extern void penv_mc_dch0_perf64event_dch0_rd_valid_count(unsigned long *count);
extern void penv_mc_dch1_perf64event_dch1_rd_valid_init();
extern void penv_mc_dch1_perf64event_dch1_rd_valid_count(unsigned long *count);
extern void penv_mc_dch0_perf65event_dch0_wr_valid_init();
extern void penv_mc_dch0_perf65event_dch0_wr_valid_count(unsigned long *count);
extern void penv_mc_dch1_perf65event_dch1_wr_valid_init();
extern void penv_mc_dch1_perf65event_dch1_wr_valid_count(unsigned long *count);
/*****************************************/
extern void penv_get_comm_sr_bytes(unsigned long *, unsigned long *); 
extern void penv_commuicate_rs_data_count(long *v,double *tc);
extern void penv_comm_rs_band_tic(void);
extern double penv_comm_rs_band_toc(void);
extern void penv_commuicate_recv_data_count(long *v,double *tc);
extern void penv_comm_recv_band_tic(void);
extern double penv_comm_recv_band_toc(void);
extern void penv_commuicate_send_data_count(long *v,double *tc);
extern void penv_comm_send_band_tic(void);
extern double penv_comm_send_band_toc(void);

extern void penv_get_io_rw_bytes(unsigned long *, unsigned long *); 
extern void penv_io_rw_byte_count(long *v,double *tc);
extern void penv_io_rw_band_tic(void);
extern double penv_io_rw_band_toc(void);
extern void penv_io_read_byte_count(long *v,double *tc);
extern void penv_io_read_band_tic(void);
extern double penv_io_read_band_toc(void);
extern void penv_io_write_byte_count(long *v,double *tc);
extern void penv_io_write_band_tic(void);
extern double penv_io_write_band_toc(void);
extern void penv_slave_spec_gld_init();
extern void penv_slave_spec_gld_count(unsigned long *count); 
/*****************************************/

struct pmu_counter{
    int cid;
    int cnt_event;
    int rdlen;
    int default_event;
    char *name;
	void (*start)(int,int);
	void (*read)(int,unsigned long *);
	void (*stop)(int);
};

struct _ext_dat{
	unsigned long hc_0,hc_1;
	unsigned long comm_0,comm_1;
	unsigned long io_0,io_1;
};
extern int is_default_evt;  //is default evt set  
extern struct pmu_counter pmucnt_list[];
extern int CNTLIST_SIZE;
extern unsigned int PMURES_SIZE;
extern unsigned long pmu_result_avg[];
//#define CNTLIST_SIZE (sizeof(pmucnt_list)/sizeof(pmucnt_list[0]))
#define DEFAULT_CNFILE "/home/fpga7a/swperfstat/pmu9a.conf"
/*****************************************/
#if 0
extern void penv_host_pcr_init(int cid, int sel);
extern void penv_host_pcr_read(int cid,unsigned long *); 
extern void penv_host_pcr_stop(int cid);
extern void penv_host_specpcr_init(int cid, int sel);
extern void penv_host_specpcr_read(int cid,unsigned long *); 
extern void penv_host_specpcr_stop(int cid);
extern void penv_cg_pcr_init(int cid, int sel);
extern void penv_cg_pcr_read(int cid,unsigned long *); 
extern void penv_cg_pcr_stop(int cid);
extern void penv_cg_scmtpcr_init(int cid, int sel);
extern void penv_cg_scmtpcr_read(int cid,unsigned long *);
extern void penv_cg_scmtpcr_stop(int cid);
extern void penv_mc_init(int cid, int sel);
extern void penv_mc_read(int cid,unsigned long *);
extern void penv_mc_stop(int cid);
#endif
/****************************************/
#ifndef PENV_PERF_SLAVE_API_INIT
	#define PENV_PERF_SLAVE_API_INIT penv_slave0_cycle_init 
#endif
#ifndef PENV_PERF_SLAVE_API_COUNT
	#define PENV_PERF_SLAVE_API_COUNT penv_slave0_cycle_count 
#endif
/****************************************/
extern int index_pmures[];
extern unsigned long pmu_result[];
#define PMU_RESULT_OFFSET(id_offset,idx) (pmu_result[index_pmures[id_offset]+idx])
#define PMU_RESULT_CID(cid,idx) (pmu_result[index_pmures[ID_offset(cid)]+idx])
extern void pmu_uai_start(int cid,int eid);
extern void pmu_uai_read(int cid,unsigned long *val);
extern void pmu_uai_stop(int cid);

extern char *event_name(int cid,int event);
extern char *counter_name(int cid);
//extern int check_event(int cid,int event);
extern struct _ext_dat extdat;
extern void output_default(FILE *fp);
extern void output_non_default(FILE *fp);
#ifdef __cplusplus
}
#endif
#endif
