 extern	 double sin(double );
 extern  double sind(double );
 extern  float  sinf(float );
 extern  float  sindf(float );
 extern  double cos(double );
 extern  double cosd(double );
 extern  float  cosf(float );
 extern  float  cosdf(float );
 extern  double tan(double );
 extern  double tand(double );
 extern  float  tanf(float );
 extern  float  tandf(float );
 extern  double cot(double );
 extern  double cotd(double );
 extern  float  cotf(float );
 extern  float  cotdf(float );
 extern  double asin(double );
 extern  double asind(double );
 extern  float  asinf(float );
 extern  float  asindf(float );
 extern  double acos(double );
 extern  double acosd(double );
 extern  float  acosf(float );
 extern  float  acosdf(float );
 extern  double atan(double );
 extern  double atand(double );
 extern  float  atanf(float );
 extern  float  atandf(float );
 extern  double atan2(double ,double );
 extern  double atand2(double ,double );
 extern  float  atan2f(float ,float );
 extern  float  atand2f(float ,float );

 extern  double sinh(double );
 extern  float  sinhf(float );
 extern  double cosh(double );
 extern  float  coshf(float );
 extern  double tanh(double );
 extern  float  tanhf(float );
 extern  double asinh(double );
 extern  float  asinhf(float );
 extern  double acosh(double );
 extern  float  acoshf(float );
 extern  double atanh(double );
 extern  float  atanhf(float );

 extern  double erf(double );
 extern  float  erff(float );
 extern  double erfc(double );
 extern  float  erfcf(float );

 extern  double exp(double );
 extern  float  expf(float );
 extern  double exp2(double );
 extern  float  exp2f(float );
 extern  double expm1(double );
 extern  float  expm1f(float );
 extern  double log(double );
 extern  float  logf(float );
 extern  double log1p(double );
 extern  float  log1pf(float );
 extern  double log2(double );
 extern  float  log2f(float );
 extern  double log10(double );
 extern  float  log10f(float );
 extern  double pow(double ,double );
 extern  float  powf(float ,float );
 extern  int    ilogb(double );
 extern  int    ilogbf(float );
  extern  double ceil(double );
  extern  float  ceilf(float );
  extern  double floor(double );
  extern  float  floorf(float );
  extern  double rint(double );
  extern  float  rintf(float );
  extern  double nearbyint(double );
  extern  float  nearbyintf(float );
  extern  double nint(double );
  extern  float  nintf(float );
  extern  double round(double );
  extern  float  roundf(float );
  extern   long  lrint(double );
  extern   long  lrintf(float );
  extern   long  lround(double );
  extern   long  lroundf(float );
  extern  double trunc(double );
  extern  float  truncf(float );
  extern  double fmod(double ,double);
  extern  float  fmodf(float ,float );
  extern  double remainder(double ,double);
  extern  float  remainderf(float ,float);
  extern  double drem(double ,double);
  extern  float  dremf(float ,float);
  extern  double modf(double ,double *);
  extern  float  modff(float ,float *);
  extern  double remquo(double ,double ,int *);
  extern  float  remquof(float ,float ,int *);

  extern  double sqrt(double );
  extern  float  sqrtf(float );
  extern  double cbrt(double );
  extern  float  cbrtf(float );

  extern  double lgamma(double );
  extern  float  lgammaf(float );

  extern  double frexp(double ,int *);
  extern  float  frexpf(float ,int *);
  extern  double ldexp(double ,int );
  extern  float  ldexpf(float ,int );
  extern  double logb(double );
  extern  float  logbf(float );
  extern  double scalb(double ,double );
  extern  float  scalbf(float ,float );
  extern  double scalbln(double ,long );
  extern  float  scalblnf(float ,long );
  extern  double scalbn(double ,int );
  extern  float  scalbnf(float ,int );

  extern  double j0(double );
  extern  float  j0f(float );
  extern  double j1(double );
  extern  float  j1f(float );
  extern  double jn(int ,double );
  extern  float  jnf(int ,float );
  extern  double y0(double );
  extern  float  y0f(float );
  extern  double y1(double );
  extern  float  y1f(float );
  extern  double yn(int ,double );
  extern  float  ynf(int ,float );

  extern  int    isnan(double );
  extern  int    isnanf(float );
  extern  int    finite(double );
  extern  int    finitef(float );
  extern  int    fp_class(double );
  extern  int    fp_classf(float );
  extern  double nextafter(double ,double );
  extern  float  nextafterf(float ,float );
  extern  double nextbefore(double ,double );
  extern  float  nextbeforef(float ,float );
  extern  int    unordered(double ,double );
  extern  int    unorderedf(float ,float );
  extern  double copysign(double ,double );
  extern  float  copysignf(float ,float );

  extern  double hypot(double ,double );
  extern  float  hypotf(float ,float );
  extern  double cabs(double ,double );
  extern  float  cabsf(float ,float );
  extern  double fabs(double );
  extern  float  fabsf(float );
  extern  double fdim(double ,double );
  extern  float  fdimf(float ,float );
  extern  double fmax(double ,double );
  extern  float  fmaxf(float ,float );
  extern  double fmin(double ,double );
  extern  float  fminf(float ,float );
  extern  double fma(double ,double ,double );
  extern  float  fmaf(float ,float ,float );

  extern  double copysign(double ,double );
  extern  float  copysignf(float ,float );
  extern  double fabs(double );
  extern  float  fabsf(float );
  extern  double fma(double ,double ,double );
  extern  float  fmaf(float ,float ,float );

  extern  double __sin_vo(double ,long );
  extern  float  __sin_vof(float ,long );
  extern  double __cos_vo(double ,long );
  extern  float  __cos_vof(float ,long );
  extern  void   __sincos_vo(double * ,double ,long );
  extern  void   __sincos_vof(float * ,float ,long );






  extern  double __sin(double );
  extern  double __sind(double );
  extern  float  __sinf(float );
  extern  float  __sindf(float );
  extern  double __cos(double );
  extern  double __cosd(double );
  extern  float  __cosf(float );
  extern  float  __cosdf(float );
  extern  double __tan(double );
  extern  double __tand(double );
  extern  float  __tanf(float );
  extern  float  __tandf(float );
  extern  double __cot(double );
  extern  double __cotd(double );
  extern  float  __cotf(float );
  extern  float  __cotdf(float );
  extern  double __asin(double );
  extern  double __asind(double );
  extern  float  __asinf(float );
  extern  float  __asindf(float );
  extern  double __acos(double );
  extern  double __acosd(double );
  extern  float  __acosf(float );
  extern  float  __acosdf(float );
  extern  double __atan(double );
  extern  double __atand(double );
  extern  float  __atanf(float );
  extern  float  __atandf(float );
  extern  double __atan2(double ,double );
  extern  double __atand2(double ,double );
  extern  float  __atan2f(float ,float );
  extern  float  __atand2f(float ,float );

  extern  double __sinh(double );
  extern  float  __sinhf(float );
  extern  double __cosh(double );
  extern  float  __coshf(float );
  extern  double __tanh(double );
  extern  float  __tanhf(float );
  extern  double __asinh(double );
  extern  float  __asinhf(float );
  extern  double __acosh(double );
  extern  float  __acoshf(float );
  extern  double __atanh(double );
  extern  float  __atanhf(float );

  extern  double __erf(double );
  extern  float  __erff(float );
  extern  double __erfc(double );
  extern  float  __erfcf(float );

  extern  double __exp(double );
  extern  float  __expf(float );
  extern  double __exp2(double );
  extern  float  __exp2f(float );
  extern  double __expm1(double );
  extern  float  __expm1f(float );
  extern  double __log(double );
  extern  float  __logf(float );
  extern  double __log1p(double );
  extern  float  __log1pf(float );
  extern  double __log2(double );
  extern  float  __log2f(float );
  extern  double __log10(double );
  extern  float  __log10f(float );
  extern  double __pow(double ,double );
  extern  float  __powf(float ,float );
  extern  int    __ilogb(double );
  extern  int    __ilogbf(float );

  extern  double __ceil(double );
  extern  float  __ceilf(float );
  extern  double __floor(double );
  extern  float  __floorf(float );
  extern  double __rint(double );
  extern  float  __rintf(float );
  extern  double __nearbyint(double );
  extern  float  __nearbyintf(float );
  extern  double __nint(double );
  extern  float  __nintf(float );
  extern  double __round(double );
  extern  float  __roundf(float );
  extern   long  __lrint(double );
  extern   long  __lrintf(float );
  extern   long  __lround(double );
  extern   long  __lroundf(float );
  extern  double __trunc(double );
  extern  float  __truncf(float );
  extern  double __fmod(double ,double);
  extern  float  __fmodf(float ,float );
  extern  double __remainder(double ,double);
  extern  float  __remainderf(float ,float);
  extern  double __drem(double ,double);
  extern  float  __dremf(float ,float);
  extern  double __modf(double ,double *);
  extern  float  __modff(float ,float *);
  extern  double __remquo(double ,double ,int *);
  extern  float  __remquof(float ,float ,int *);

  extern  double __sqrt(double );
  extern  float  __sqrtf(float );
  extern  double __cbrt(double );
  extern  float  __cbrtf(float );

  extern  double __lgamma(double );
  extern  float  __lgammaf(float );

  extern  double __frexp(double ,int *);
  extern  float  __frexpf(float ,int *);
  extern  double __ldexp(double ,int );
  extern  float  __ldexpf(float ,int );
  extern  double __logb(double );
  extern  float  __logbf(float );
  extern  double __scalb(double ,double );
  extern  float  __scalbf(float ,float );
  extern  double __scalbln(double ,long );
  extern  float  __scalblnf(float ,long );
  extern  double __scalbn(double ,int );
  extern  float  __scalbnf(float ,int );

  extern  double __j0(double );
  extern  float  __j0f(float );
  extern  double __j1(double );
  extern  float  __j1f(float );
  extern  double __jn(int ,double );
  extern  float  __jnf(int ,float );
  extern  double __y0(double );
  extern  float  __y0f(float );
  extern  double __y1(double );
  extern  float  __y1f(float );
  extern  double __yn(int ,double );
  extern  float  __ynf(int ,float );

  extern  int    __isnan(double );
  extern  int    __isnanf(float );
  extern  int    __finite(double );
  extern  int    __finitef(float );
  extern  int    __fp_class(double );
  extern  int    __fp_classf(float );
  extern  double __nextafter(double ,double );
  extern  float  __nextafterf(float ,float );
  extern  double __nextbefore(double ,double );
  extern  float  __nextbeforef(float ,float );
  extern  int    __unordered(double ,double );
  extern  int    __unorderedf(float ,float );
  extern  double __copysign(double ,double );
  extern  float  __copysignf(float ,float );

  extern  double __hypot(double ,double );
  extern  float  __hypotf(float ,float );
  extern  double __cabs(double ,double );
  extern  float  __cabsf(float ,float );
  extern  double __fabs(double );
  extern  float  __fabsf(float );
  extern  double __fdim(double ,double );
  extern  float  __fdimf(float ,float );
  extern  double __fmax(double ,double );
  extern  float  __fmaxf(float ,float );
  extern  double __fmin(double ,double );
  extern  float  __fminf(float ,float );
  extern  double __fma(double ,double ,double );
  extern  float  __fmaf(float ,float ,float );

  extern  double __copysign(double ,double );
  extern  float  __copysignf(float ,float );
  extern  double __fabs(double );
  extern  float  __fabsf(float );
  extern  double __fma(double ,double ,double );
  extern  float  __fmaf(float ,float ,float );

